/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentMerchantData : NSObject {
    NSData *_applicationData;
    NSString *_merchantIdentifier;
}

@property(assign,retain) NSData * applicationData;
@property(assign,retain) NSString * merchantIdentifier;

- (id)applicationData;
- (void)dealloc;
- (id)encode;
- (id)merchantIdentifier;
- (void)setApplicationData:(id)arg1;
- (void)setMerchantIdentifier:(id)arg1;

@end
