/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSDialogButton : NSObject {
    NSDictionary *_actionDictionary;
    NSString *_title;
}

@property(assign,readonly) NSString * URLTarget;
@property(assign,readonly) id actionParameter;
@property(assign,readonly) NSString * buttonAction;
@property(assign,copy) NSString * buttonTitle;

+ (id)buttonWithTitle:(id)arg1;

- (id)URLTarget;
- (id)actionParameter;
- (id)buttonAction;
- (id)buttonTitle;
- (void)dealloc;
- (id)init;
- (id)initWithTitle:(id)arg1 actionDictionary:(id)arg2;
- (id)valueForActionProperty:(id)arg1;

@end
