/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSRentalCheckoutRequest : SSRequest <SSXPCCoding> {
    NSNumber *_accountIdentifier;
    long long _downloadIdentifier;
    NSNumber *_rentalKeyIdentifier;
    bool _shouldValidateRentalInfo;
    NSArray *_sinfs;
}

@property(assign,readonly) NSNumber * accountIdentifier;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) long long downloadIdentifier;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) NSNumber * rentalKeyIdentifier;
@property(assign,readwrite) bool shouldValidateRentalInfo;
@property(assign,readonly) NSArray * sinfs;
@property(assign,readonly) Class superclass;

- (id)accountIdentifier;
- (id)copyXPCEncoding;
- (void)dealloc;
- (long long)downloadIdentifier;
- (id)init;
- (id)initWithAccountIdentifier:(id)arg1 rentalKeyIdentifier:(id)arg2;
- (id)initWithDownloadIdentifier:(long long)arg1;
- (id)initWithSinfs:(id)arg1;
- (id)initWithXPCEncoding:(id)arg1;
- (id)rentalKeyIdentifier;
- (void)setShouldValidateRentalInfo:(bool)arg1;
- (bool)shouldValidateRentalInfo;
- (id)sinfs;
- (void)startWithCompletionBlock:(id)arg1;
- (void)startWithConnectionResponseBlock:(id)arg1;

@end
