/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface PFUbiquityTransactionEntryLight : NSObject {
    NSString *_actingPeerID;
    PFUbiquityGlobalObjectID *_globalID;
    PFUbiquityKnowledgeVector *_kv;
    NSString *_storeName;
    NSDate *_transactionDate;
    PFUbiquityLocation *_transactionLogLocation;
    NSNumber *_transactionNumber;
    int _transactionType;
}

@property(assign,retain) NSString * actingPeerID;
@property(assign,retain) PFUbiquityGlobalObjectID * globalID;
@property(assign,retain) PFUbiquityKnowledgeVector * knowledgeVector;
@property(assign,retain) NSString * storeName;
@property(assign,retain) NSDate * transactionDate;
@property(assign,retain) PFUbiquityLocation * transactionLogLocation;
@property(assign,retain) NSNumber * transactionNumber;
@property(assign,readwrite) int transactionType;

- (id)actingPeerID;
- (void)dealloc;
- (id)description;
- (id)globalID;
- (id)init;
- (id)initWithTransactionEntry:(id)arg1 ubiquityRootLocation:(id)arg2 andGlobalIDCache:(id)arg3;
- (id)knowledgeVector;
- (void)setActingPeerID:(id)arg1;
- (void)setGlobalID:(id)arg1;
- (void)setKnowledgeVector:(id)arg1;
- (void)setStoreName:(id)arg1;
- (void)setTransactionDate:(id)arg1;
- (void)setTransactionLogLocation:(id)arg1;
- (void)setTransactionNumber:(id)arg1;
- (void)setTransactionType:(int)arg1;
- (id)storeName;
- (id)transactionDate;
- (id)transactionLogLocation;
- (id)transactionNumber;
- (int)transactionType;

@end
