/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIAirDropActivity : UIActivity {
    SFAirDropActivityViewController *_airDropViewController;
    id _airdropCompletion;
}

@property(assign,retain) SFAirDropActivityViewController * airDropViewController;
@property(assign,copy) id airdropCompletion;

- (struct CGSize { double x1; double x2; })_thumbnailSize;
- (id)activityType;
- (id)airDropViewController;
- (id)airdropCompletion;
- (void)dealloc;
- (void)performActivity;
- (void)prepareWithActivityItems:(id)arg1;
- (void)setAirDropViewController:(id)arg1;
- (void)setAirdropCompletion:(id)arg1;

@end
