/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarStyleAnimationParameters : UIStatusBarAnimationParameters {
    int _styleAnimation;
}

@property(assign,readwrite) int styleAnimation;

- (id)initWithDefaultParameters;
- (void)setStyleAnimation:(int)arg1;
- (bool)shouldAnimate;
- (int)styleAnimation;

@end
