/* Generated by RuntimeBrowser.
 */

@protocol GEOMapRoad <GEOMapLine>

@required

- (GEOMapRequest *)findRoadsFrom:(id)arg1 completionHandler:(/* Warning: Unrecognized filer type: '?' using 'void*' */ void*)arg2;
- (int)formOfWay;
- (int)roadClass;

@end
