/* Generated by RuntimeBrowser.
 */

@protocol IKJSPlaylist <JSExport>

@required

- (IKJSMediaItem *)currentMediaItem;
- (id)init;
- (IKJSMediaItem *)item:(long long)arg1;
- (unsigned long long)length;
- (IKJSMediaItem *)nextMediaItem;
- (IKJSMediaItem *)pop;
- (IKJSMediaItem *)previousMediaItem;
- (unsigned long long)push:(JSValue *)arg1;
- (NSArray *)splice:(JSValue *)arg1 :(JSValue *)arg2 :(JSValue *)arg3;

@end
