/* Generated by RuntimeBrowser.
 */

@protocol MPUNowPlayingPlaybackControlsViewDelegate <MPPlaybackControlsDelegate>

@optional

- (void)playbackControls:(MPUNowPlayingPlaybackControlsView *)arg1 didSelectCreateAction:(long long)arg2;

@end
