/* Generated by RuntimeBrowser.
 */

@protocol MTLFunction <NSObject>

@required

- (<MTLDevice> *)device;
- (unsigned long long)functionType;
- (NSString *)name;
- (NSArray *)vertexAttributes;

@end
