/* Generated by RuntimeBrowser.
 */

@protocol MusicJSProfileNativeViewController <JSExport, MusicJSNativeViewController>

@required

- (void)presentShareDocument:(IKDOMDocument *)arg1 :(NSDictionary *)arg2;
- (void)setBiographyDocument:(IKDOMDocument *)arg1 :(NSDictionary *)arg2;
- (void)setProfileEntityValueProvider:(NSDictionary *)arg1;
- (void)setSegmentDocument:(NSString *)arg1 :(IKDOMDocument *)arg2 :(NSDictionary *)arg3;
- (void)setVisibleSegments:(NSArray *)arg1;

@end
