/* Generated by RuntimeBrowser.
 */

@protocol NSURLSessionDelegate <NSObject>

@optional

- (void)URLSession:(NSURLSession *)arg1 didBecomeInvalidWithError:(NSError *)arg2;
- (void)URLSession:(NSURLSession *)arg1 didReceiveChallenge:(NSURLAuthenticationChallenge *)arg2 completionHandler:(id)arg3;
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(NSURLSession *)arg1;

@end
