/* Generated by RuntimeBrowser.
 */

@protocol PKPaymentVerificationPresentationDelegate

@required

- (void)didChangeVerificationPresentation;
- (void)presentVerificationViewController:(UIViewController *)arg1 animated:(bool)arg2 completion:(id)arg3;

@end
