/* Generated by RuntimeBrowser.
 */

@protocol PLAlbumContainer <PLAssetContainerList>

@required

- (NSString *)_prettyDescription;
- (NSString *)_typeDescription;
- (bool)albumHasFixedOrder:(struct NSObject { Class x1; }*)arg1;
- (short)albumListType;
- (NSMutableOrderedSet *)albums;
- (unsigned long long)albumsCount;
- (id)albumsSortingComparator:(long long)arg1;
- (bool)canEditAlbums;
- (int)filter;
- (bool)hasAtLeastOneAlbum;
- (NSNumber *)identifier;
- (bool)isFolder;
- (bool)needsReordering;
- (void)preheatAlbumsAtIndexes:(NSIndexSet *)arg1 forProperties:(NSArray *)arg2 relationships:(NSArray *)arg3;
- (void)preheatAlbumsForProperties:(NSArray *)arg1 relationships:(NSArray *)arg2;
- (void)setNeedsReordering;
- (unsigned long long)unreadAlbumsCount;
- (void)updateAlbumsOrderIfNeeded;

@end
