/* Generated by RuntimeBrowser.
 */

@protocol PRSDescriptionSection <PRSSection>

@required

- (NSString *)resultDescription;
- (void)setResultDescription:(NSString *)arg1;

@optional

- (bool)description_expand;
- (NSString *)description_expand_text;
- (long long)description_maxlines;
- (long long)description_size;
- (long long)description_weight;
- (PRSImage *)image;
- (NSString *)image_align;
- (void)setDescription_expand:(bool)arg1;
- (void)setDescription_expand_text:(NSString *)arg1;
- (void)setDescription_maxlines:(long long)arg1;
- (void)setDescription_size:(long long)arg1;
- (void)setDescription_weight:(long long)arg1;
- (void)setImage:(PRSImage *)arg1;
- (void)setImage_align:(NSString *)arg1;
- (void)setTitle:(NSString *)arg1;
- (void)setTitle_nowrap:(bool)arg1;
- (void)setTitle_weight:(long long)arg1;
- (NSString *)title;
- (bool)title_nowrap;
- (long long)title_weight;

@end
