/* Generated by RuntimeBrowser.
 */

@protocol QLPreviewContentControllerProtocol <NSObject>

@required

- (void)becomeForeground;
- (void)beginScrubbing;
- (void)checkCurrentPreviewItem;
- (void)configureWithParameters:(NSDictionary *)arg1;
- (long long)currentPreviewItemIndex;
- (<QLPreviewContentDataSource> *)dataSource;
- (<QLPreviewContentDelegate> *)delegate;
- (void)endScrubbing;
- (void)enterBackground;
- (void)forceResignFirstResponder;
- (int)previewMode;
- (<QLRemotePrintPageHelper> *)printPageHelper;
- (QLPrintPageRenderer *)printPageRenderer;
- (void)refreshCurrentPreviewItem;
- (void)scrubToValue:(double)arg1;
- (void)setBlockRemoteImages:(bool)arg1;
- (void)setContentFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setCurrentPreviewItemIndex:(long long)arg1;
- (void)setDataSource:(id <QLPreviewContentDataSource>)arg1;
- (void)setDelegate:(id <QLPreviewContentDelegate>)arg1;
- (void)setLoadingTextForMissingFiles:(NSString *)arg1;
- (void)setOverlayHidden:(bool)arg1 duration:(double)arg2;
- (void)setPreviewMode:(int)arg1;
- (void)setTransitioning:(bool)arg1 synchronizedWithBlock:(id)arg2;
- (void)stopLoadingCurrentPreviewItem;
- (void)togglePlayState;
- (void)willChangeContentFrame;

@end
