/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AASetupAssistantConfigResponse : AAResponse {
    NSDictionary *_urls;
}

@property(assign,readonly) NSString * aboutURL;
@property(assign,readonly) NSString * activeEmailDomain;
@property(assign,readonly) NSString * authenticateURL;
@property(assign,readonly) NSString * checkValidityURL;
@property(assign,readonly) NSString * createAppleIDURL;
@property(assign,readonly) NSString * createDelegateAccountsURL;
@property(assign,readonly) NSString * existingAppleIDTermsUIURL;
@property(assign,readonly) NSString * genericTermsURL;
@property(assign,readonly) NSString * iForgotUIURL;
@property(assign,readonly) NSString * iForgotURL;
@property(assign,readonly) NSString * loginDelegatesURL;
@property(assign,readonly) bool setupAssistantServerEnabled;
@property(assign,readonly) NSString * signingSessionCertURL;
@property(assign,readonly) NSString * signingSessionURL;
@property(assign,readonly) NSString * updateAppleIDURL;
@property(assign,readonly) NSString * upgradeIOSTermsUI;
@property(assign,readonly) NSString * upgradeStatusURL;
@property(assign,readonly) NSString * xmlUI;

- (void).cxx_destruct;
- (id)aboutURL;
- (id)activeEmailDomain;
- (id)authenticateURL;
- (id)checkValidityURL;
- (id)createAppleIDURL;
- (id)createDelegateAccountsURL;
- (id)existingAppleIDTermsUIURL;
- (id)genericTermsURL;
- (id)iForgotUIURL;
- (id)iForgotURL;
- (id)initWithHTTPResponse:(id)arg1 data:(id)arg2;
- (id)loginDelegatesURL;
- (bool)setupAssistantServerEnabled;
- (id)signingSessionCertURL;
- (id)signingSessionURL;
- (id)updateAppleIDURL;
- (id)upgradeIOSTermsUI;
- (id)upgradeStatusURL;
- (id)xmlUI;

@end
