/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUFeedSectionInfosChange : NSObject {
    NSIndexSet *_deletedIndexes;
    NSIndexSet *_insertedIndexes;
    NSSet *_sectionInfosWithCommentChanges;
    bool _shouldReload;
    NSSet *_updatedAssets;
    NSIndexSet *_updatedIndexes;
}

@property(assign,retain) NSIndexSet * deletedIndexes;
@property(assign,retain) NSIndexSet * insertedIndexes;
@property(assign,retain) NSSet * sectionInfosWithCommentChanges;
@property(assign,readwrite) bool shouldReload;
@property(assign,retain) NSSet * updatedAssets;
@property(assign,retain) NSIndexSet * updatedIndexes;

- (void).cxx_destruct;
- (id)deletedIndexes;
- (id)insertedIndexes;
- (id)sectionInfosWithCommentChanges;
- (void)setDeletedIndexes:(id)arg1;
- (void)setInsertedIndexes:(id)arg1;
- (void)setSectionInfosWithCommentChanges:(id)arg1;
- (void)setShouldReload:(bool)arg1;
- (void)setUpdatedAssets:(id)arg1;
- (void)setUpdatedIndexes:(id)arg1;
- (bool)shouldReload;
- (id)updatedAssets;
- (id)updatedIndexes;

@end
