/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicEntityProviderChangeRecord : NSObject <NSCopying> {
    NSIndexPath *_destinationIndexPath;
    <MusicEntityValueProviding> *_entityValueProvider;
    NSIndexPath *_sourceIndexPath;
    long long _type;
}

@property(assign,readonly) <MusicEntityValueProviding> * deletedEntityValueProvider;
@property(assign,readonly) NSIndexPath * deletedIndexPath;
@property(assign,readonly) <MusicEntityValueProviding> * insertedEntityValueProvider;
@property(assign,readonly) NSIndexPath * insertedIndexPath;
@property(assign,readonly) NSIndexPath * moveDestinationIndexPath;
@property(assign,readonly) NSIndexPath * moveSourceIndexPath;
@property(assign,readonly) <MusicEntityValueProviding> * movedEntityValueProvider;
@property(assign,readonly) long long type;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)deletedEntityValueProvider;
- (id)deletedIndexPath;
- (id)description;
- (id)initWithDeletedEntityValueProvider:(id)arg1 atIndexPath:(id)arg2;
- (id)initWithInsertedEntityValueProvider:(id)arg1 atIndexPath:(id)arg2;
- (id)initWithMovedEntityValueProvider:(id)arg1 fromSourceIndexPath:(id)arg2 toDestinationIndexPath:(id)arg3;
- (id)insertedEntityValueProvider;
- (id)insertedIndexPath;
- (id)moveDestinationIndexPath;
- (id)moveSourceIndexPath;
- (id)movedEntityValueProvider;
- (long long)type;

@end
