/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicEntityViewContentTextDescriptor : NSObject <NSCopying> {
    id _attributedTextProvider;
    long long _backdropOverlayBlendMode;
    UIColor *_backgroundColor;
    double _defaultFirstBaselineOffset;
    double _displayScale;
    MPUFontDescriptor *_fontDescriptor;
    long long _lineBreakMode;
    double _maximumHeight;
    long long _maximumNumberOfLines;
    long long _maximumTextLengthForInput;
    bool _needsTextAttributesUpdate;
    double _scaledFirstBaselineOffset;
    double _tallestFontAscender;
    double _tallestFontBodyLeading;
    double _tallestFontCapHeight;
    double _tallestFontDescender;
    long long _textAlignment;
    UIColor *_textColor;
    MPUTextDrawingCache *_textDrawingCache;
    NSString *_textPlaceholder;
    UIColor *_textPlaceholderColor;
    id _textProvider;
    NSString *_textValueFallbackLocalizationIdentifier;
    NSString *_textValueProperty;
}

@property(assign,copy) id attributedTextProvider;
@property(assign,readwrite) long long backdropOverlayBlendMode;
@property(assign,retain) UIColor * backgroundColor;
@property(assign,readwrite) double defaultFirstBaselineOffset;
@property(assign,readwrite) double displayScale;
@property(assign,copy) MPUFontDescriptor * fontDescriptor;
@property(assign,readwrite) long long lineBreakMode;
@property(assign,readonly) double maximumHeight;
@property(assign,readwrite) long long maximumNumberOfLines;
@property(assign,readwrite) long long maximumTextLengthForInput;
@property(assign,readonly) double scaledFirstBaselineOffset;
@property(assign,readonly) double tallestFontAscender;
@property(assign,readonly) double tallestFontBodyLeading;
@property(assign,readonly) double tallestFontCapHeight;
@property(assign,readonly) double tallestFontDescender;
@property(assign,readwrite) long long textAlignment;
@property(assign,retain) UIColor * textColor;
@property(assign,readonly) MPUTextDrawingCache * textDrawingCache;
@property(assign,copy) NSString * textPlaceholder;
@property(assign,retain) UIColor * textPlaceholderColor;
@property(assign,copy) id textProvider;
@property(assign,copy) NSString * textValueFallbackLocalizationIdentifier;
@property(assign,copy) NSString * textValueProperty;

- (void).cxx_destruct;
- (id)_tallestFont;
- (void)_updateTextAttributes;
- (id)attributedTextProvider;
- (long long)backdropOverlayBlendMode;
- (id)backgroundColor;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)defaultFirstBaselineOffset;
- (double)displayScale;
- (id)fontDescriptor;
- (id)init;
- (long long)lineBreakMode;
- (double)maximumHeight;
- (long long)maximumNumberOfLines;
- (long long)maximumTextLengthForInput;
- (double)scaledFirstBaselineOffset;
- (void)setAttributedTextProvider:(id)arg1;
- (void)setBackdropOverlayBlendMode:(long long)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setDefaultFirstBaselineOffset:(double)arg1;
- (void)setDisplayScale:(double)arg1;
- (void)setFontDescriptor:(id)arg1;
- (void)setLineBreakMode:(long long)arg1;
- (void)setMaximumNumberOfLines:(long long)arg1;
- (void)setMaximumTextLengthForInput:(long long)arg1;
- (void)setTextAlignment:(long long)arg1;
- (void)setTextColor:(id)arg1;
- (void)setTextPlaceholder:(id)arg1;
- (void)setTextPlaceholderColor:(id)arg1;
- (void)setTextProvider:(id)arg1;
- (void)setTextValueFallbackLocalizationIdentifier:(id)arg1;
- (void)setTextValueProperty:(id)arg1;
- (double)tallestFontAscender;
- (double)tallestFontBodyLeading;
- (double)tallestFontCapHeight;
- (double)tallestFontDescender;
- (long long)textAlignment;
- (id)textColor;
- (id)textDrawingCache;
- (id)textForEntityValueProvider:(id)arg1;
- (id)textPlaceholder;
- (id)textPlaceholderColor;
- (id)textProvider;
- (id)textValueFallbackLocalizationIdentifier;
- (id)textValueProperty;
- (void)updateForPreferredContentSizeChange;

@end
