/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPDLocalizedSpokenStructuredAddress : PBCodable <NSCopying> {
    NSString *_locale;
    GEOStructuredAddress *_spokenStructuredAddress;
}

@property(assign,readonly) bool hasLocale;
@property(assign,readonly) bool hasSpokenStructuredAddress;
@property(assign,retain) NSString * locale;
@property(assign,retain) GEOStructuredAddress * spokenStructuredAddress;

- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasLocale;
- (bool)hasSpokenStructuredAddress;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)locale;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setLocale:(id)arg1;
- (void)setSpokenStructuredAddress:(id)arg1;
- (id)spokenStructuredAddress;
- (void)writeTo:(id)arg1;

@end
