/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOSuggestionEntryList : PBCodable <NSCopying> {
    NSString *_localizedSectionHeader;
    NSMutableArray *_suggestionEntries;
}

@property(assign,readonly) bool hasLocalizedSectionHeader;
@property(assign,retain) NSString * localizedSectionHeader;
@property(assign,retain) NSMutableArray * suggestionEntries;

- (void)addSuggestionEntries:(id)arg1;
- (void)clearSuggestionEntries;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasLocalizedSectionHeader;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)localizedSectionHeader;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setLocalizedSectionHeader:(id)arg1;
- (void)setSuggestionEntries:(id)arg1;
- (id)suggestionEntries;
- (id)suggestionEntriesAtIndex:(unsigned long long)arg1;
- (unsigned long long)suggestionEntriesCount;
- (void)writeTo:(id)arg1;

@end
