/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Search.framework/Search
 */

@interface SPSearchResultSection : PBCodable <NSCopying> {
    NSString *_category;
    NSString *_displayIdentifier;
    unsigned int _domain;
    int _flags;
    struct { 
        unsigned int domain : 1; 
        unsigned int flags : 1; 
    } _has;
    NSString *_icon;
    NSMutableOrderedSet *_resultSet;
    NSString *_scheme;
}

@property (nonatomic, retain) NSString *category;
@property (nonatomic, retain) NSString *displayIdentifier;
@property (nonatomic) unsigned int domain;
@property (nonatomic) int flags;
@property (nonatomic, readonly) bool hasCategory;
@property (nonatomic, readonly) bool hasDisplayIdentifier;
@property (nonatomic) bool hasDomain;
@property (nonatomic) bool hasFlags;
@property (nonatomic, readonly) bool hasIcon;
@property (nonatomic, readonly) bool hasScheme;
@property (nonatomic, retain) NSString *icon;
@property (nonatomic, retain) NSString *scheme;

- (void)addResults:(id)arg1;
- (void)addResults:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)category;
- (void)clearResults;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayIdentifier;
- (unsigned int)domain;
- (int)flags;
- (bool)hasCategory;
- (bool)hasDisplayIdentifier;
- (bool)hasDomain;
- (bool)hasEquivalentResults:(id)arg1;
- (bool)hasFlags;
- (bool)hasIcon;
- (bool)hasScheme;
- (unsigned long long)hash;
- (id)icon;
- (unsigned long long)indexOfResult:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)removeResultsAtIndex:(unsigned long long)arg1;
- (id)resultSet;
- (id)results;
- (id)resultsAtIndex:(unsigned long long)arg1;
- (unsigned long long)resultsCount;
- (id)scheme;
- (void)setCategory:(id)arg1;
- (void)setDisplayIdentifier:(id)arg1;
- (void)setDomain:(unsigned int)arg1;
- (void)setFlags:(int)arg1;
- (void)setHasDomain:(bool)arg1;
- (void)setHasFlags:(bool)arg1;
- (void)setIcon:(id)arg1;
- (void)setScheme:(id)arg1;
- (void)writeTo:(id)arg1;

@end
