/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface SFUCryptoKey : NSObject <TSPMutableCryptoInfo> {
    NSString *_passphrase;
    unsigned int mIterationCount;
    char *mKey;
    unsigned long long mKeyLength;
    NSData *mSaltData;
}

@property(assign,readonly) NSArray * blockInfos;
@property(assign,readonly) SFUCryptoKey * cryptoKey;
@property(assign,copy) NSString * debugDescription;
@property(assign,readonly) unsigned long long decodedLength;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) NSString * passphrase;
@property(assign,readonly) unsigned long long preferredBlockSize;
@property(assign,readonly) Class superclass;

- (void)addBlockInfo:(id)arg1;
- (id)blockInfos;
- (id)cryptoKey;
- (void)dealloc;
- (unsigned long long)decodedLength;
- (void)incrementDecodedLengthBy:(unsigned long long)arg1;
- (id)initAes128Key:(const char *)arg1 length:(unsigned int)arg2 iterationCount:(unsigned int)arg3;
- (id)initAes128KeyFromPassphrase:(id)arg1 iterationCount:(unsigned int)arg2;
- (id)initAes128KeyFromPassphrase:(id)arg1 iterationCount:(unsigned int)arg2 saltData:(id)arg3;
- (id)initAes128KeyFromPassphrase:(const char *)arg1 length:(unsigned int)arg2 iterationCount:(unsigned int)arg3;
- (id)initAes128KeyFromPassphrase:(const char *)arg1 length:(unsigned int)arg2 iterationCount:(unsigned int)arg3 saltData:(id)arg4;
- (id)initAes128KeyFromPassphrase:(id)arg1 withIterationCountAndSaltDataFromCryptoKey:(id)arg2;
- (unsigned int)iterationCount;
- (const char *)keyData;
- (unsigned long long)keyLength;
- (int)keyType;
- (id)mutableCryptoInfoCopy;
- (id)passphrase;
- (unsigned long long)preferredBlockSize;
- (void)reset;
- (id)saltData;

@end
