/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TPPaginatedPageInfo : TPPageInfo

@property(assign,readonly) NSArray * floatingDrawableInfos;
@property(assign,readonly) bool isDocumentSetupPage;

- (id)floatingDrawableInfos;
- (bool)isDocumentSetupPage;
- (Class)layoutClass;
- (id)pageController;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })pageFrame;
- (Class)repClass;

@end
