/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSDMutableCurvedShadow : TSDCurvedShadow

@property(assign,copy) TSUColor * TSUColor;
@property(assign,readwrite) double angle;
@property(assign,readwrite) struct CGColor { }* color;
@property(assign,readwrite) double curve;
@property(getter=isEnabled,assign,readwrite) bool enabled;
@property(assign,readwrite) double offset;
@property(assign,readwrite) double opacity;
@property(assign,readwrite) double radius;

- (void)setAngle:(double)arg1;
- (void)setColor:(struct CGColor { }*)arg1;
- (void)setCurve:(double)arg1;
- (void)setOffset:(double)arg1;
- (void)setOpacity:(double)arg1;
- (void)setRadius:(double)arg1;
- (void)setTSUColor:(id)arg1;

@end
