/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/PerformanceAnalysis
 */

@interface PAAggregatedInstruction : PACountedFrame {
    NSUUID *_binaryUuid;
    NSMutableSet *_children;
    unsigned long long _offsetInBinary;
}

@property(assign,readonly) NSUUID * binaryUuid;
@property(assign,retain) NSMutableSet * children;
@property(assign,readonly) bool isKernel;
@property(assign,readonly) unsigned long long offsetInBinary;

- (id)binaryUuid;
- (id)children;
- (long long)compare:(id)arg1;
- (void)dealloc;
- (unsigned long long)hash;
- (id)initWithUUID:(id)arg1 andOffset:(unsigned long long)arg2 isKernel:(bool)arg3;
- (bool)isEqual:(id)arg1;
- (bool)isKernel;
- (unsigned long long)offsetInBinary;
- (void)setChildren:(id)arg1;

@end
