/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/PerformanceAnalysis
 */

@interface PASampleTaskData : NSObject <PASerializable> {
    NSSet *_donatingPids;
    PASampleTaskDataPrivateData *_privateData;
    PASampleTimeInsensitiveTaskData *_timeInsensitiveTaskData;
    NSArray *sampleThreadsArray;
}

@property(assign,readonly) bool allowsIdleExit;
@property(assign,readonly) NSString * bundleName;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,retain) NSSet * donatingPids;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) NSArray * imageInfos;
@property(assign,readonly) bool isBoosted;
@property(assign,readonly) bool isDarwinBG;
@property(assign,readonly) bool isDarwinExtBG;
@property(assign,readonly) bool isDirty;
@property(assign,readonly) bool isForeground;
@property(assign,readonly) bool isFrozen;
@property(assign,readonly) bool isNonVisible;
@property(assign,readonly) bool isPidSuspended;
@property(assign,readonly) bool isSuppressed;
@property(assign,readonly) bool isTaskResourceFlagged;
@property(assign,readonly) bool isTerminatedSnapshot;
@property(assign,readonly) bool isThirdParty;
@property(assign,readonly) bool isTimerThrottled;
@property(assign,readonly) bool isUnresponsive;
@property(assign,readonly) bool isVisible;
@property(assign,readonly) unsigned int latency_qos;
@property(assign,readonly) unsigned long long mainBinaryOffset;
@property(assign,readonly) NSString * mainBinaryPath;
@property(assign,readonly) NSUUID * mainBinaryUuid;
@property(assign,readonly) NSString * name;
@property(assign,readonly) int numberOfCopyOnWritePageFaults;
@property(assign,readonly) int numberOfPageFaults;
@property(assign,readonly) int numberOfPageIns;
@property(assign,readonly) int pid;
@property(assign,readonly) int ppid;
@property(assign,readonly) int rpid;
@property(assign,readonly) unsigned long long sharedCacheLength;
@property(assign,readonly) unsigned long long sharedCacheOffset;
@property(assign,readonly) unsigned long long sharedCacheStart;
@property(assign,readonly) NSUUID * sharedCacheUUID;
@property(assign,readonly) unsigned int ss_flags;
@property(assign,readonly) Class superclass;
@property(assign,readonly) int suspendCount;
@property(assign,readonly) int taskSizeInPages;
@property(assign,readonly) double timeOfLastResponse;
@property(assign,readonly) unsigned int uid;
@property(assign,readonly) unsigned long long uniqueId;
@property(assign,readonly) bool usesSuddenTermination;
@property(assign,readonly) bool workQueueExceededConstrainedThreadLimit;
@property(assign,readonly) bool workQueueExceededTotalThreadLimit;

+ (id)classDictionaryKey;
+ (id)newInstanceWithoutReferencesFromBufferPosition:(const void*)arg1;

- (bool)addSelfToBufferAtPosition:(void*)arg1 withCompletedSerializationDictionary:(id)arg2;
- (void)addSelfToSerializationDictionary:(id)arg1;
- (bool)allowsIdleExit;
- (id)architectureString;
- (id)bundleName;
- (void)dealloc;
- (id)description;
- (id)donatingPids;
- (id)imageInfos;
- (id)initWithStackshotTask:(id)arg1 andTimeInsensitiveTaskData:(id)arg2;
- (bool)isBoosted;
- (bool)isDarwinBG;
- (bool)isDarwinExtBG;
- (bool)isDirty;
- (bool)isForeground;
- (bool)isFrozen;
- (bool)isNonVisible;
- (bool)isPidSuspended;
- (bool)isSameAsTask:(id)arg1;
- (bool)isSuppressed;
- (bool)isTaskResourceFlagged;
- (bool)isTerminatedSnapshot;
- (bool)isThirdParty;
- (bool)isTimerThrottled;
- (bool)isUnresponsive;
- (bool)isVisible;
- (unsigned int)latency_qos;
- (unsigned long long)mainBinaryOffset;
- (id)mainBinaryPath;
- (id)mainBinaryUuid;
- (id)name;
- (int)numberOfCopyOnWritePageFaults;
- (int)numberOfPageFaults;
- (int)numberOfPageIns;
- (int)pid;
- (void)populateReferencesUsingBufferPosition:(const void*)arg1 andDeserializationDictionary:(id)arg2 andDataBufferDictionary:(id)arg3;
- (int)ppid;
- (int)rpid;
- (void)setDonatingPids:(id)arg1;
- (unsigned long long)sharedCacheLength;
- (unsigned long long)sharedCacheOffset;
- (unsigned long long)sharedCacheStart;
- (id)sharedCacheUUID;
- (unsigned long long)sizeInBytesForSerializedVersion;
- (unsigned int)ss_flags;
- (int)suspendCount;
- (int)taskSizeInPages;
- (id)timeInsensitiveTaskData;
- (double)timeOfLastResponse;
- (unsigned int)uid;
- (unsigned long long)uniqueId;
- (bool)usesSuddenTermination;
- (bool)workQueueExceededConstrainedThreadLimit;
- (bool)workQueueExceededTotalThreadLimit;

@end
