/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDPowerManager : NSObject {
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    bool _ethernetActive;
    bool _networkAccessRequired;
    unsigned int _powerAssertion;
    void *_scContext;
    struct __SCDynamicStore { } *_scStore;
    bool _started;
}

@property(getter=isNetworkAccessRequired,assign,readwrite) bool networkAccessRequired;

- (void).cxx_destruct;
- (int)_ensureNetworkInterfaceMonitorStarted;
- (void)_ensureNetworkInterfaceMonitorStopped;
- (void)_update;
- (void)dealloc;
- (id)init;
- (bool)isNetworkAccessRequired;
- (void)setNetworkAccessRequired:(bool)arg1;
- (void)start;
- (void)stop;

@end
