/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
 */

@interface RCTrimSavedRecordingOperation : RCTrimCompositionOperation {
    RCSavedRecording *_destinationRecording;
    RCSavedRecording *_sourceRecording;
}

@property(assign,readonly) RCSavedRecording * destinationRecording;
@property(assign,readonly) RCSavedRecording * sourceRecording;

- (void).cxx_destruct;
- (id)destinationRecording;
- (id)initWithSourceRecording:(id)arg1 destinationRecording:(id)arg2 timeRange:(struct { double x1; double x2; })arg3 trimMode:(long long)arg4;
- (void)main;
- (id)sourceRecording;

@end
