/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAAceDomainSignal : SABaseClientBoundCommand

@property(assign,copy) NSString * domain;

+ (id)aceDomainSignal;
+ (id)aceDomainSignalWithDictionary:(id)arg1 context:(id)arg2;

- (id)domain;
- (id)encodedClassName;
- (id)groupIdentifier;
- (bool)requiresResponse;
- (void)setDomain:(id)arg1;

@end
