/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAMicroblogAceMicroblogSearchResult : SADomainObject

@property(assign,retain) SAMicroblogTwitterPostAuthor * globalAuthor;
@property(assign,retain) SAUIAppPunchOut * punchOut;
@property(assign,copy) NSString * query;
@property(assign,copy) NSArray * resultNews;
@property(assign,copy) NSArray * resultPosts;
@property(assign,copy) NSArray * resultUsers;
@property(assign,retain) SADecoratedString * summary;
@property(assign,copy) NSURL * webAddress;

+ (id)aceMicroblogSearchResult;
+ (id)aceMicroblogSearchResultWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;
- (id)globalAuthor;
- (id)groupIdentifier;
- (id)punchOut;
- (id)query;
- (id)resultNews;
- (id)resultPosts;
- (id)resultUsers;
- (void)setGlobalAuthor:(id)arg1;
- (void)setPunchOut:(id)arg1;
- (void)setQuery:(id)arg1;
- (void)setResultNews:(id)arg1;
- (void)setResultPosts:(id)arg1;
- (void)setResultUsers:(id)arg1;
- (void)setSummary:(id)arg1;
- (void)setWebAddress:(id)arg1;
- (id)summary;
- (void)updateUsingSet:(id)arg1 add:(id)arg2 remove:(id)arg3;
- (id)webAddress;

@end
