/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SASSpeechRecognized : SABaseClientBoundCommand

@property (nonatomic, retain) SASRecognition *recognition;
@property (nonatomic, copy) NSString *sessionId;

+ (id)speechRecognized;
+ (id)speechRecognizedWithDictionary:(id)arg1 context:(id)arg2;

- (id)af_bestTextInterpretation;
- (id)af_correctionContext;
- (id)af_userUtteranceValue;
- (id)encodedClassName;
- (id)groupIdentifier;
- (id)recognition;
- (bool)requiresResponse;
- (id)sessionId;
- (void)setRecognition:(id)arg1;
- (void)setSessionId:(id)arg1;

@end
