/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SASTBodyTextItem : AceObject <SASTTemplateItem>

@property(assign,copy) NSString * bodyText;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

+ (id)bodyTextItem;
+ (id)bodyTextItemWithDictionary:(id)arg1 context:(id)arg2;

- (id)bodyText;
- (id)encodedClassName;
- (id)groupIdentifier;
- (void)setBodyText:(id)arg1;

@end
