/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TouchRemote.framework/TouchRemote
 */

@interface TRDeviceSetupBrowser : NSObject <TRTransferBrowserDelegate> {
    <TRDeviceSetupBrowserDelegate> *_delegate;
    TRDeviceSetupPeripheral *_peripheral;
    TRTransferBrowser *_transferBrowser;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <TRDeviceSetupBrowserDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) long long state;
@property(assign,readonly) Class superclass;

- (void).cxx_destruct;
- (id)browser:(id)arg1 didReceiveData:(id)arg2;
- (void)browserDidChangeState:(id)arg1;
- (void)browserDidDisconnect:(id)arg1;
- (id)browserDidStartTransfer:(id)arg1;
- (void)defer;
- (id)delegate;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)start;
- (long long)state;
- (void)stop;

@end
