/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SASportsMetadata : AceObject <SAAceSerializable>

@property(assign,copy) NSNumber * average;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,copy) NSString * identifier;
@property(assign,copy) NSString * name;
@property(assign,copy) NSNumber * selected;
@property(assign,readonly) Class superclass;
@property(assign,copy) NSString * value;

+ (id)metadata;
+ (id)metadataWithDictionary:(id)arg1 context:(id)arg2;

- (id)average;
- (id)encodedClassName;
- (id)groupIdentifier;
- (id)identifier;
- (id)name;
- (id)selected;
- (void)setAverage:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setName:(id)arg1;
- (void)setSelected:(id)arg1;
- (void)setValue:(id)arg1;
- (id)value;

@end
