/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SASStartCorrectedSpeechRequest : SAStartRequest

@property(assign,copy) NSString * interactionId;
@property(assign,copy) NSString * sessionId;

+ (id)startCorrectedSpeechRequest;
+ (id)startCorrectedSpeechRequestWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;
- (id)groupIdentifier;
- (id)interactionId;
- (id)sessionId;
- (void)setInteractionId:(id)arg1;
- (void)setSessionId:(id)arg1;

@end
