/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SASTCompetingTeamPlayDetailItem : AceObject <SASTTemplateItem>

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readwrite) bool firstEntity;
@property(assign,readonly) unsigned long long hash;
@property(assign,retain) SAUIDecoratedText * playDetail;
@property(assign,readonly) Class superclass;

+ (id)competingTeamPlayDetailItem;
+ (id)competingTeamPlayDetailItemWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;
- (bool)firstEntity;
- (id)groupIdentifier;
- (id)playDetail;
- (void)setFirstEntity:(bool)arg1;
- (void)setPlayDetail:(id)arg1;

@end
