/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AARequest : NSObject <NSURLSessionDataDelegate> {
    struct OpaqueCFHTTPCookieStorage { } *_cookieStorage;
    bool _flushCache;
    id _handler;
    NSString *_initialURLString;
    NSString *_machineId;
    NSString *_oneTimePassword;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readwrite) bool flushCache;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;
@property(assign,readonly) NSURLRequest * urlRequest;

+ (id)protocolVersion;
+ (Class)responseClass;

- (void).cxx_destruct;
- (void)_handleDataTaskCompletionWithData:(id)arg1 response:(id)arg2 error:(id)arg3;
- (id)_redactedHeadersFromHTTPHeaders:(id)arg1;
- (id)bodyDictionary;
- (void)dealloc;
- (bool)flushCache;
- (id)initWithURLString:(id)arg1;
- (void)performRequestWithHandler:(id)arg1;
- (id)redactedBodyStringWithPropertyList:(id)arg1;
- (void)setCookieStorage:(struct OpaqueCFHTTPCookieStorage { }*)arg1;
- (void)setDeviceProvisioningMachineId:(id)arg1;
- (void)setDeviceProvisioningOneTimePassword:(id)arg1;
- (void)setFlushCache:(bool)arg1;
- (id)urlCredential;
- (id)urlRequest;
- (id)urlString;

@end
