/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PowerlogCore.framework/PowerlogCore
 */

@interface PLSQLStatement : NSObject {
    NSMutableArray *_boundObjects;
    struct sqlite3 { } *_dbConnection;
    bool _isDelete;
    bool _isInsert;
    NSString *_sqlQuery;
    struct sqlite3_stmt { } *_statement;
    NSString *_syncObject;
}

@property(assign,retain) NSMutableArray * boundObjects;
@property(assign,readwrite) struct sqlite3 { }* dbConnection;
@property(assign,readonly) bool isDelete;
@property(assign,readonly) bool isInsert;
@property(assign,retain) NSString * sqlQuery;
@property(assign,readwrite) struct sqlite3_stmt { }* statement;
@property(assign,retain) NSString * syncObject;

- (void).cxx_destruct;
- (int)bindValue:(id)arg1 withFormater:(short)arg2 atPosition:(int)arg3;
- (id)boundObjects;
- (struct sqlite3 { }*)dbConnection;
- (void)dealloc;
- (id)description;
- (void)finalize;
- (id)initWithSQLQuery:(id)arg1 forDatabase:(struct sqlite3 { }*)arg2 withSyncObject:(id)arg3 result:(int*)arg4;
- (bool)isDelete;
- (bool)isInsert;
- (id)perform;
- (void)reset;
- (void)setBoundObjects:(id)arg1;
- (void)setDbConnection:(struct sqlite3 { }*)arg1;
- (void)setSqlQuery:(id)arg1;
- (void)setStatement:(struct sqlite3_stmt { }*)arg1;
- (void)setSyncObject:(id)arg1;
- (id)sqlQuery;
- (struct sqlite3_stmt { }*)statement;
- (id)syncObject;

@end
