/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface PFUbiquitySwitchboardCacheWrapper : NSObject {
    bool _allowSchedulingOfReceiptFileWrites;
    PFUbiquityKnowledgeVector *_baselineKV;
    PFUbiquityGlobalObjectIDCache *_globalIDCache;
    PFUbiquityKnowledgeVector *_kv;
    NSString *_localPeerID;
    PFUbiquityPeerRangeCache *_peerRangeCache;
    PFUbiquityPeerReceipt *_peerReceipt;
    bool _pendingReceiptWrite;
    NSLock *_receiptFileLock;
    NSString *_storeName;
    PFUbiquityTransactionHistoryCache *_transactionHistoryCache;
    PFUbiquityTransactionLogCache *_transactionLogCache;
    PFUbiquityLocation *_ubiquityRootLocation;
}

@property(assign,retain) PFUbiquityKnowledgeVector * baselineKV;
@property(assign,readonly) PFUbiquityGlobalObjectIDCache * globalIDCache;
@property(assign,retain) PFUbiquityKnowledgeVector * kv;
@property(assign,readonly) NSString * localPeerID;
@property(assign,readonly) PFUbiquityPeerRangeCache * peerRangeCache;
@property(assign,readonly) PFUbiquityPeerReceipt * peerReceipt;
@property(assign,readonly) NSString * storeName;
@property(assign,readonly) PFUbiquityTransactionHistoryCache * transactionHistoryCache;
@property(assign,readonly) PFUbiquityTransactionLogCache * transactionLogCache;
@property(assign,retain) PFUbiquityLocation * ubiquityRootLocation;

- (void)_appWillResignActive:(id)arg1;
- (id)baselineKV;
- (void)cacheWrapperWillBeRemovedFromEntry;
- (void)dealloc;
- (id)globalIDCache;
- (id)init;
- (id)initWithStoreName:(id)arg1 privateStore:(id)arg2 forLocalPeerID:(id)arg3 andUbiquityRootLocation:(id)arg4;
- (id)kv;
- (id)localPeerID;
- (id)peerRangeCache;
- (id)peerReceipt;
- (void)scheduleReceiptFileWrite:(id)arg1;
- (void)setBaselineKV:(id)arg1;
- (void)setKv:(id)arg1;
- (void)setUbiquityRootLocation:(id)arg1;
- (id)storeName;
- (id)transactionHistoryCache;
- (id)transactionLogCache;
- (id)ubiquityRootLocation;
- (bool)writeReceiptFile:(bool)arg1 error:(id*)arg2;

@end
