/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKPlatform : NSObject {
    bool _lowPerformanceDevice;
    unsigned long long _memSize;
    int _numCPUs;
    bool _proceduralRoadAlpha;
    bool _shouldUseTrafficAlphaHack;
    bool _supports3DBuildingStrokes;
    bool _supportsBuildingStrokes;
    bool _useCheapTrafficShader;
}

@property (nonatomic, readonly) bool canMakeSharingThumbnails;
@property (nonatomic, readonly) bool isPad;
@property (nonatomic, readonly) bool lowPerformanceDevice;
@property (nonatomic, readonly) double mainScreenPPI;
@property (nonatomic, readonly) double mainScreenScale;
@property (nonatomic, readonly) double maxContentScaleForRendering;
@property (nonatomic, readonly) unsigned long long memorySize;
@property (nonatomic, readonly) bool proceduralRoadAlpha;
@property (nonatomic, readonly) bool roadsWithSimpleLineMeshesAvailable;
@property (nonatomic, readonly) double routeLineSimplificationEpsilon;
@property (nonatomic, readonly) bool shouldDrawWhenReady;
@property (nonatomic, readonly) bool shouldPregenerateLabelGlyphs;
@property (nonatomic, readonly) bool shouldStyleLabelsInParallel;
@property (nonatomic, readonly) bool shouldUseTrafficAlphaHack;
@property (nonatomic, readonly) bool supports3DBuildingStrokes;
@property (nonatomic, readonly) bool supports3DBuildings;
@property (nonatomic, readonly) bool supportsBuildingShadows;
@property (nonatomic, readonly) bool supportsBuildingStrokes;
@property (nonatomic, readonly) bool supportsHiResBuildings;
@property (nonatomic, readonly) bool supportsHiResRTT;
@property (nonatomic, readonly) unsigned int tileDecodeQueueWidth;
@property (nonatomic, readonly) unsigned long long tileMaximumLimit;
@property (nonatomic, readonly) unsigned int tilePrefetchNumberOfScreens;
@property (nonatomic, readonly) bool useCheapTrafficShader;

+ (id)sharedPlatform;

- (unsigned long long)_calculateMemSize;
- (void)_determineHardware;
- (bool)canMakeSharingThumbnails;
- (void)dealloc;
- (id)init;
- (bool)isPad;
- (bool)lowPerformanceDevice;
- (double)mainScreenPPI;
- (double)mainScreenScale;
- (double)maxContentScaleForRendering;
- (unsigned long long)memorySize;
- (bool)proceduralRoadAlpha;
- (bool)roadsWithSimpleLineMeshesAvailable;
- (double)routeLineSimplificationEpsilon;
- (bool)shouldDrawWhenReady;
- (bool)shouldPregenerateLabelGlyphs;
- (bool)shouldStyleLabelsInParallel;
- (bool)shouldUseTrafficAlphaHack;
- (bool)supports3DBuildingStrokes;
- (bool)supports3DBuildings;
- (bool)supportsBuildingShadows;
- (bool)supportsBuildingStrokes;
- (bool)supportsHiResBuildings;
- (bool)supportsHiResRTT;
- (unsigned int)tileDecodeQueueWidth;
- (unsigned long long)tileMaximumLimit;
- (unsigned int)tilePrefetchNumberOfScreens;
- (unsigned long long)tileReserveLimit:(bool)arg1;
- (bool)useCheapTrafficShader;

@end
