/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKSkyDrawStyle : VKRenderStyle

@property(assign,readonly) /* Warning: unhandled struct encoding: '{Matrix<float' */ struct  fillColor; /* unknown property attribute:  1>=[4f]} */
@property(assign,readonly) /* Warning: unhandled struct encoding: '{Matrix<float' */ struct  horizonColor; /* unknown property attribute:  1>=[4f]} */

+ (int)renderStyleID;

- (struct Matrix<float, 4, 1> { float x1[4]; })fillColor;
- (struct Matrix<float, 4, 1> { float x1[4]; })horizonColor;

@end
