/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface _HKQueryServerDataObject : NSObject <NSSecureCoding> {
    _HKFilter *_filter;
    HKSampleType *_sampleType;
    bool _shouldStayAliveAfterInitialResults;
}

@property(assign,retain) _HKFilter * filter;
@property(assign,retain) HKSampleType * sampleType;
@property(assign,readwrite) bool shouldStayAliveAfterInitialResults;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)filter;
- (id)initWithCoder:(id)arg1;
- (id)sampleType;
- (void)setFilter:(id)arg1;
- (void)setSampleType:(id)arg1;
- (void)setShouldStayAliveAfterInitialResults:(bool)arg1;
- (bool)shouldStayAliveAfterInitialResults;

@end
