/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKAchievement : NSObject <HDCoding, NSSecureCoding> {
    NSUUID *_UUID;
    unsigned long long _achievementType;
    NSDate *_completedDate;
    NSNumber *_value;
    bool _viewed;
}

@property (nonatomic, retain) NSUUID *UUID;
@property (nonatomic) unsigned long long achievementType;
@property (nonatomic, retain) NSDate *completedDate;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSData *extraData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSNumber *value;
@property (getter=isViewed, nonatomic) bool viewed;

+ (unsigned long long)_achievementTypeFromString:(id)arg1;
+ (id)_achievementTypeNameMappings;
+ (id)_achievementWithUUID:(id)arg1 type:(unsigned long long)arg2 completedDate:(id)arg3 value:(id)arg4 extraData:(id)arg5;
+ (id)_allAchievementTypeNames;
+ (Class)_classForAchievementType:(unsigned long long)arg1;
+ (id)_nextUUID;
+ (bool)_requiresValueForAchievementType:(unsigned long long)arg1;
+ (id)achievementWithAchievementType:(unsigned long long)arg1 completedDate:(id)arg2 value:(id)arg3;
+ (id)achievementWithAchievementType:(unsigned long long)arg1 completedDate:(id)arg2 value:(id)arg3 workoutActivityType:(unsigned long long)arg4;
+ (id)createWithCodable:(id)arg1;
+ (void)setOverridenUUID:(id)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)UUID;
- (id)_achievementTypeString;
- (void)_decodeExtraDataWithCoder:(id)arg1;
- (void)_encodeExtraDataWithCoder:(id)arg1;
- (id)_fiui_URLForFullMovieName:(id)arg1 withScale:(double)arg2;
- (id)_fiui_assetNameForSizeClass:(long long)arg1;
- (bool)_hasExtraData;
- (id)_localizedDescriptionForCompleteNumberOfTimes:(long long)arg1;
- (id)_localizedDescriptionForIncomplete;
- (bool)_validateConfiguration;
- (unsigned long long)achievementType;
- (id)codableRepresentationForSync;
- (id)completedDate;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)extraData;
- (id)fiui_badgeMovieURL;
- (id)fiui_imageForSizeClass:(long long)arg1;
- (unsigned long long)hash;
- (id)initWithAchievementType:(unsigned long long)arg1 completedDate:(id)arg2 value:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isViewed;
- (id)localizedDescription;
- (id)localizedDescriptionForAlertWithUserName:(id)arg1;
- (id)localizedDescriptionWithNumberOfTimesAchieved:(long long)arg1;
- (id)localizedTitle;
- (void)setAchievementType:(unsigned long long)arg1;
- (void)setCompletedDate:(id)arg1;
- (void)setExtraData:(id)arg1;
- (void)setUUID:(id)arg1;
- (void)setValue:(id)arg1;
- (void)setViewed:(bool)arg1;
- (id)value;

@end
