/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDCustomAssetImportInfo : NSObject {
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    } _alignmentRect;
    NSObject<TDCustomAssetSource> *_customAsset;
    NSString *_elementName;
    NSDate *_modificationDate;
    NSString *_name;
    NSString *_partName;
    CUIRenditionKey *_renditionKey;
    long long _renditionType;
    struct CGSize { 
        double width; 
        double height; 
    } _resizableSliceSize;
    long long _resizingMode;
    struct { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _sliceInsets;
    long long _templateRenderingMode;
}

@property(assign,readwrite) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } alignmentRect;
@property(assign,retain) NSObject<TDCustomAssetSource> * customAsset;
@property(assign,copy) NSString * elementName;
@property(assign,readwrite) bool isTemplate;
@property(assign,copy) NSDate * modificationDate;
@property(assign,copy) NSString * name;
@property(assign,copy) NSString * partName;
@property(assign,copy) CUIRenditionKey * renditionKey;
@property(assign,readwrite) long long renditionType;
@property(assign,readwrite) struct CGSize { double x1; double x2; } resizableSliceSize;
@property(assign,readwrite) long long resizingMode;
@property(assign,readwrite) struct { double x1; double x2; double x3; double x4; } sliceInsets;
@property(assign,readwrite) long long templateRenderingMode;

- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })alignmentRect;
- (id)customAsset;
- (void)dealloc;
- (id)elementName;
- (bool)isTemplate;
- (id)modificationDate;
- (id)name;
- (id)partName;
- (id)renditionKey;
- (long long)renditionSubtype;
- (long long)renditionType;
- (struct CGSize { double x1; double x2; })resizableSliceSize;
- (long long)resizingMode;
- (void)setAlignmentRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setCustomAsset:(id)arg1;
- (void)setElementName:(id)arg1;
- (void)setIsTemplate:(bool)arg1;
- (void)setModificationDate:(id)arg1;
- (void)setName:(id)arg1;
- (void)setPartName:(id)arg1;
- (void)setRenditionKey:(id)arg1;
- (void)setRenditionType:(long long)arg1;
- (void)setResizableSliceSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setResizingMode:(long long)arg1;
- (void)setSliceInsets:(struct { double x1; double x2; double x3; double x4; })arg1;
- (void)setTemplateRenderingMode:(long long)arg1;
- (struct { double x1; double x2; double x3; double x4; })sliceInsets;
- (long long)templateRenderingMode;

@end
