/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDMetafontSelector : TDThemeConstant

@property(assign,retain) TDFontDefinition * definition;

@end
