/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/EventKit.framework/EventKit
 */

@interface EKTravelPrediction : NSObject <NSSecureCoding> {
    NSDate *_arrivalDate;
    NSDate *_departureDate;
    NSDate *_predictionDate;
    CLLocation *_startingLocation;
    double _ttl;
    double _validRadius;
}

@property(assign,readonly) <EKTravelAdvice> * advice;
@property(assign,readonly) NSDate * arrivalDate;
@property(assign,readonly) NSDate * departureDate;
@property(assign,readonly) NSDate * predictionDate;
@property(assign,readonly) CLLocation * startingLocation;
@property(assign,readonly) double ttl;
@property(assign,readonly) double validRadius;

+ (bool)supportsSecureCoding;

- (id)advice;
- (id)arrivalDate;
- (void)dealloc;
- (id)departureDate;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDepartureDate:(id)arg1 arrivalDate:(id)arg2 startingLocation:(id)arg3 predictionDate:(id)arg4 pollAggressively:(bool)arg5;
- (id)initWithDepartureDate:(id)arg1 arrivalDate:(id)arg2 startingLocation:(id)arg3 validRadius:(double)arg4 predictionDate:(id)arg5 ttl:(double)arg6;
- (bool)isExpiredWithLocation:(id)arg1 date:(id)arg2;
- (id)predictionDate;
- (id)startingLocation;
- (double)ttl;
- (double)validRadius;

@end
