/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantUI.framework/AssistantUI
 */

@interface AFUIRequestOptions : NSObject <NSCopying, NSSecureCoding> {
    bool _acousticIdEnabled;
    NSString *_appBundleIdentifier;
    NSString *_bluetoothDeviceAddress;
    AFBulletin *_bulletin;
    NSDictionary *_continuityInfo;
    long long _directActionEvent;
    double _expectedTimestamp;
    NSNumber *_homeButtonUpFromBeep;
    bool _initialBringUp;
    NSDictionary *_messagesDirectActionContext;
    SASPronunciationContext *_pronunciationContext;
    bool _pronunciationRequest;
    long long _requestSource;
    NSString *_serverCommandId;
    NSURL *_speechFileURL;
    NSString *_text;
    double _timestamp;
    bool _useAutomaticEndpointing;
    bool _useStreamingDictation;
}

@property(assign,readwrite) bool acousticIdEnabled;
@property(assign,copy) NSString * appBundleIdentifier;
@property(assign,copy) NSString * bluetoothDeviceAddress;
@property(assign,retain) AFBulletin * bulletin;
@property(assign,copy) NSDictionary * continuityInfo;
@property(assign,readwrite) long long directActionEvent;
@property(assign,readwrite) double expectedTimestamp;
@property(getter=isForSpeechRequest,assign,readonly) bool forSpeechRequest;
@property(getter=isForStark,assign,readonly) bool forStark;
@property(assign,retain) NSNumber * homeButtonUpFromBeep;
@property(getter=isInitialBringUp,assign,readwrite) bool initialBringUp;
@property(assign,copy) NSDictionary * messagesDirectActionContext;
@property(assign,retain) SASPronunciationContext * pronunciationContext;
@property(getter=isPronunciationRequest,assign,readwrite) bool pronunciationRequest;
@property(assign,readwrite) long long requestSource;
@property(assign,copy) NSString * serverCommandId;
@property(assign,copy) NSURL * speechFileURL;
@property(assign,copy) NSString * text;
@property(assign,readwrite) double timestamp;
@property(assign,readwrite) bool useAutomaticEndpointing;
@property(assign,readwrite) bool useStreamingDictation;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_configureStreamingDictationForSource:(long long)arg1;
- (bool)acousticIdEnabled;
- (id)appBundleIdentifier;
- (id)bluetoothDeviceAddress;
- (id)bulletin;
- (id)continuityInfo;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (long long)directActionEvent;
- (void)encodeWithCoder:(id)arg1;
- (double)expectedTimestamp;
- (id)homeButtonUpFromBeep;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithRequestSource:(long long)arg1;
- (bool)isForSpeechRequest;
- (bool)isForStark;
- (bool)isInitialBringUp;
- (bool)isPronunciationRequest;
- (id)messagesDirectActionContext;
- (id)pronunciationContext;
- (long long)requestSource;
- (id)serverCommandId;
- (void)setAcousticIdEnabled:(bool)arg1;
- (void)setAppBundleIdentifier:(id)arg1;
- (void)setBluetoothDeviceAddress:(id)arg1;
- (void)setBulletin:(id)arg1;
- (void)setContinuityInfo:(id)arg1;
- (void)setDirectActionEvent:(long long)arg1;
- (void)setExpectedTimestamp:(double)arg1;
- (void)setHomeButtonUpFromBeep:(id)arg1;
- (void)setInitialBringUp:(bool)arg1;
- (void)setMessagesDirectActionContext:(id)arg1;
- (void)setPronunciationContext:(id)arg1;
- (void)setPronunciationRequest:(bool)arg1;
- (void)setRequestSource:(long long)arg1;
- (void)setServerCommandId:(id)arg1;
- (void)setSpeechFileURL:(id)arg1;
- (void)setText:(id)arg1;
- (void)setTimestamp:(double)arg1;
- (void)setUseAutomaticEndpointing:(bool)arg1;
- (void)setUseStreamingDictation:(bool)arg1;
- (id)speechFileURL;
- (id)text;
- (double)timestamp;
- (bool)useAutomaticEndpointing;
- (bool)useStreamingDictation;

@end
