/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKETAResponse : NSObject {
    MKMapItem *_destination;
    double _distance;
    double _expectedTravelTime;
    NSArray *_sortedETAs;
    MKMapItem *_source;
}

@property(assign,readonly) MKMapItem * destination;
@property(getter=_distance,assign,readonly) double distance;
@property(assign,readonly) double expectedTravelTime;
@property(getter=_sortedETAs,assign,readonly) NSArray * sortedETAs;
@property(assign,readonly) MKMapItem * source;

- (void).cxx_destruct;
- (double)_distance;
- (id)_sortedETAs;
- (id)destination;
- (double)expectedTravelTime;
- (id)initWithSource:(id)arg1 destination:(id)arg2 expectedTravelTime:(double)arg3 distance:(double)arg4 sortedETAs:(id)arg5;
- (id)source;

@end
