/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXHearingAidSupport.framework/AXHearingAidSupport
 */

@interface AXHearingAidDetailCell : PSTableCell {
    bool _bluetoothAvailable;
    AXRemoteHearingAidDevice *_device;
    UIImageView *_leftBattery;
    UILabel *_leftLabel;
    UIActivityIndicatorView *_loadingIndicator;
    NSNumberFormatter *_numberFormatter;
    UIImageView *_rightBattery;
    UILabel *_rightLabel;
}

@property (nonatomic, retain) AXRemoteHearingAidDevice *device;

- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (void)bluetoothAvailabilityDidChange:(id)arg1;
- (void)dealloc;
- (id)device;
- (id)imageForBatteryLevel:(double)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 andDevice:(id)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)layoutSubviews;
- (void)setDevice:(id)arg1;
- (void)setSelected:(bool)arg1 animated:(bool)arg2;
- (void)updateAvailability;

@end
