/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Notes.framework/Notes
 */

@interface NoteStoreObject : NoteCollectionObject

@property(assign,retain) NoteAccountObject * account;
@property(assign,retain) NSSet * changes;
@property(assign,retain) NSString * externalIdentifier;
@property(assign,retain) NSString * name;
@property(assign,retain) NSString * syncAnchor;

- (id)basicAccountIdentifier;
- (id)collectionInfo;
- (unsigned int)maximumServerIntId;
- (unsigned long long)minimumSequenceNumberForServerIntIds:(id)arg1;
- (id)notesForGUIDs:(id)arg1;
- (id)notesForIntegerIds:(id)arg1;
- (id)notesForServerIds:(id)arg1;
- (id)notesForServerIntIds:(id)arg1;
- (id)notesForServerIntIds:(id)arg1 ascending:(bool)arg2 limit:(unsigned long long)arg3;
- (id)notesForServerIntIdsInRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (id)notesForServerIntIdsInRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 ascending:(bool)arg2 limit:(unsigned long long)arg3;
- (id)predicateForNotes;

@end
