/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Accounts.framework/Accounts
 */

@interface ACAccountCredential : NSObject <NSSecureCoding> {
    NSMutableDictionary *_credentialItems;
    NSString *_credentialType;
    bool _dirty;
    NSMutableSet *_dirtyProperties;
    bool _empty;
    ACAccount *_owningAccount;
}

@property(assign,copy) NSString * credentialType;
@property(getter=isDirty,assign,readwrite) bool dirty;
@property(assign,readonly) NSSet * dirtyProperties;
@property(getter=isEmpty,assign,readwrite) bool empty;
@property(assign,retain) NSDate * expiryDate;
@property(assign,copy) NSString * findMyiPhoneToken;
@property(assign,copy) NSString * hsaToken;
@property(assign,copy) NSString * mapsToken;
@property(assign,copy) NSString * oauthRefreshToken;
@property(assign,copy) NSString * oauthToken;
@property(assign,copy) NSString * oauthTokenSecret;
@property(assign,copy) NSString * password;
@property(assign,copy) NSString * token;
@property(assign,copy) NSDate * tokenExpiryDate;

+ (id)credentialPolicyForAccountType:(id)arg1 key:(id)arg2 clientID:(id)arg3;
+ (id)credentialWithOAuthToken:(id)arg1 tokenSecret:(id)arg2;
+ (id)credentialWithPassword:(id)arg1;
+ (id)nonPersistentKeysForAccountTypeIdentifier:(id)arg1 credentialType:(id)arg2;
+ (id)supportedKeysForAccountTypeIdentifier:(id)arg1 credentialType:(id)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_clearDirtyProperties;
- (void)_markPropertyDirty:(id)arg1;
- (void)_setOwningAccount:(id)arg1;
- (id)credentialItemForKey:(id)arg1;
- (id)credentialItems;
- (id)credentialType;
- (id)dirtyProperties;
- (void)encodeWithCoder:(id)arg1;
- (id)expiryDate;
- (id)findMyiPhoneToken;
- (unsigned long long)hash;
- (id)hsaToken;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithOAuth2Token:(id)arg1 refreshToken:(id)arg2 expiryDate:(id)arg3;
- (id)initWithOAuthToken:(id)arg1 tokenSecret:(id)arg2;
- (id)initWithPassword:(id)arg1;
- (bool)isDirty;
- (bool)isEmpty;
- (bool)isEqual:(id)arg1;
- (id)keysForCredentialItems;
- (id)mapsToken;
- (id)oauthRefreshToken;
- (id)oauthToken;
- (id)oauthTokenNoSync;
- (id)oauthTokenSecret;
- (id)password;
- (void)setCredentialItem:(id)arg1 forKey:(id)arg2;
- (void)setCredentialType:(id)arg1;
- (void)setDirty:(bool)arg1;
- (void)setEmpty:(bool)arg1;
- (void)setExpiryDate:(id)arg1;
- (void)setFindMyiPhoneToken:(id)arg1;
- (void)setHsaToken:(id)arg1;
- (void)setMapsToken:(id)arg1;
- (void)setOauthRefreshToken:(id)arg1;
- (void)setOauthToken:(id)arg1;
- (void)setOauthTokenNoSync:(id)arg1;
- (void)setOauthTokenSecret:(id)arg1;
- (void)setPassword:(id)arg1;
- (void)setToken:(id)arg1;
- (void)setTokenExpiryDate:(id)arg1;
- (id)token;
- (id)tokenExpiryDate;

@end
