/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreMIDI.framework/CoreMIDI
 */

@interface MIDINetworkSession : NSObject {
    struct _MIDINetworkSessionImpl { unsigned int x1; unsigned int x2; unsigned int x3; id x4; id x5; struct ContactOrConnectionSet { bool x_6_1_1; id x_6_1_2; } x6; } *_impl;
}

@property (nonatomic) unsigned long long connectionPolicy;
@property (getter=isEnabled, nonatomic) bool enabled;
@property (nonatomic, readonly) NSString *localName;
@property (nonatomic, readonly) NSString *networkName;
@property (nonatomic, readonly) unsigned long long networkPort;

+ (id)defaultSession;

- (bool)addConnection:(id)arg1;
- (bool)addContact:(id)arg1;
- (bool)addOrRemoveConnection:(id)arg1 add:(bool)arg2;
- (unsigned long long)connectionPolicy;
- (id)connections;
- (id)contacts;
- (void)contactsChanged;
- (void)dealloc;
- (unsigned int)destinationEndpoint;
- (id)init;
- (bool)isEnabled;
- (id)localName;
- (id)networkName;
- (unsigned long long)networkPort;
- (void)refreshBonjourName;
- (bool)removeConnection:(id)arg1;
- (bool)removeContact:(id)arg1;
- (void)sessionChanged;
- (void)setConnectionPolicy:(unsigned long long)arg1;
- (void)setEnabled:(bool)arg1;
- (void)setStateToEntity;
- (unsigned int)sourceEndpoint;
- (void)updateFromEntity;

@end
