/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoMediaRemote.framework/NanoMediaRemote
 */

@interface NMRNowPlayingApplicationInfo : NSObject <NMRMediaRemoteProtobufCodable> {
    _NMRNowPlayingApplicationStateProtobuf *_protobuf;
}

@property(assign,copy) NSString * companionBundleIdentifier;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,copy) NSString * localizedDisplayName;
@property(assign,readwrite) unsigned int playbackState;
@property(assign,readonly) Class superclass;
@property(assign,copy) NSString * watchBundleIdentifier;

- (void).cxx_destruct;
- (id)companionBundleIdentifier;
- (id)init;
- (id)initWithProtobufData:(id)arg1;
- (id)localizedDisplayName;
- (unsigned int)playbackState;
- (id)protobufData;
- (void)setCompanionBundleIdentifier:(id)arg1;
- (void)setLocalizedDisplayName:(id)arg1;
- (void)setPlaybackState:(unsigned int)arg1;
- (void)setWatchBundleIdentifier:(id)arg1;
- (id)watchBundleIdentifier;

@end
