/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AdSupport.framework/AdSupport
 */

@interface ASIdentifierManager : NSObject

@property(assign,readonly) NSUUID * advertisingIdentifier;
@property(getter=isAdvertisingTrackingEnabled,assign,readonly) bool advertisingTrackingEnabled;

+ (id)sharedManager;

- (id)advertisingIdentifier;
- (bool)isAdvertisingTrackingEnabled;

@end
