/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKWebProcessPlugInNodeHandle : NSObject <WKObject> {
    struct ObjectStorage<WebKit::InjectedBundleNodeHandle> { 
        struct type { 
            unsigned char __lx[24]; 
        } data; 
    } _nodeHandle;
}

@property(assign,readwrite) bool HTMLInputElementIsAutoFilled;
@property(assign,readonly) bool HTMLInputElementIsUserEdited;
@property(assign,readonly) WKWebProcessPlugInNodeHandle * HTMLTableCellElementCellAbove;
@property(assign,readonly) bool HTMLTextAreaElementIsUserEdited;
@property(assign,readonly) struct Object { int (**x1)(); id x2; }* _apiObject;
@property(assign,readonly) struct InjectedBundleNodeHandle { int (**x1)(); id x2; struct RefPtr<WebCore::Node> { struct Node {} *x_3_1_1; } x3; }* _nodeHandle;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } elementBounds;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

+ (id)nodeHandleWithJSValue:(id)arg1 inContext:(id)arg2;

- (id).cxx_construct;
- (bool)HTMLInputElementIsAutoFilled;
- (bool)HTMLInputElementIsUserEdited;
- (id)HTMLTableCellElementCellAbove;
- (bool)HTMLTextAreaElementIsUserEdited;
- (struct Object { int (**x1)(); id x2; }*)_apiObject;
- (struct InjectedBundleNodeHandle { int (**x1)(); id x2; struct RefPtr<WebCore::Node> { struct Node {} *x_3_1_1; } x3; }*)_nodeHandle;
- (void)dealloc;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })elementBounds;
- (id)htmlIFrameElementContentFrame;
- (bool)isTextField;
- (void)setHTMLInputElementIsAutoFilled:(bool)arg1;

@end
