/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BulletinDistributorCompanion.framework/BulletinDistributorCompanion
 */

@interface BLTWatchKitAppDefinition : NSObject {
    NSString *_containerBundleID;
    bool _isInstalled;
    NSString *_watchKitAppBundleID;
}

@property(assign,readonly) NSString * containerBundleID;
@property(assign,readonly) bool isInstalled;
@property(assign,readonly) NSString * watchKitAppBundleID;

- (void).cxx_destruct;
- (id)containerBundleID;
- (id)initWithContainerBundleID:(id)arg1 watchKitAppBundleID:(id)arg2 isInstalled:(bool)arg3;
- (bool)isInstalled;
- (id)watchKitAppBundleID;

@end
