/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoAudioControl.framework/NanoAudioControl
 */

@interface NACEUVolumeLimitMessage : PBCodable <NSCopying> {
    NSString *_category;
    float _eUVolumeLimit;
    struct { 
        unsigned int eUVolumeLimit : 1; 
    } _has;
}

@property(assign,retain) NSString * category;
@property(assign,readwrite) float eUVolumeLimit;
@property(assign,readonly) bool hasCategory;
@property(assign,readwrite) bool hasEUVolumeLimit;

- (void).cxx_destruct;
- (id)category;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (float)eUVolumeLimit;
- (bool)hasCategory;
- (bool)hasEUVolumeLimit;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setCategory:(id)arg1;
- (void)setEUVolumeLimit:(float)arg1;
- (void)setHasEUVolumeLimit:(bool)arg1;
- (void)writeTo:(id)arg1;

@end
