/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIStorePageSectionContext : NSObject {
    SKUIMetricsImpressionSession *_activeMetricsImpressionSession;
    double _activePageWidth;
    UICollectionView *_collectionView;
    SKUIColorScheme *_colorScheme;
    long long _defaultPinningTransitionStyle;
    SKUIItemOfferButtonAppearance *_itemOfferButtonAppearance;
    double _landscapePageWidth;
    long long _layoutStyle;
    SKUIMetricsController *_metricsController;
    SKUIStorePageSectionsViewController *_parentViewController;
    UIColor *_placeholderColor;
    double _portraitPageWidth;
    SKUIResourceLoader *_resourceLoader;
    SKUILayoutCache *_textLayoutCache;
}

@property(assign,readonly) SKUIMetricsImpressionSession * activeMetricsImpressionSession;
@property(assign,readonly) double activePageWidth;
@property(assign,readonly) SKUIClientContext * clientContext;
@property(assign,readonly) UICollectionView * collectionView;
@property(assign,readonly) SKUIColorScheme * colorScheme;
@property(assign,readonly) long long defaultPinningTransitionStyle;
@property(assign,readonly) SKUIItemOfferButtonAppearance * itemOfferButtonAppearance;
@property(assign,readonly) double landscapePageWidth;
@property(assign,readonly) long long layoutStyle;
@property(assign,readonly) SKUIMetricsController * metricsController;
@property(assign,readonly) SKUIStorePageSectionsViewController * parentViewController;
@property(assign,readonly) UIColor * placeholderColor;
@property(assign,readonly) double portraitPageWidth;
@property(assign,readonly) SKUIResourceLoader * resourceLoader;
@property(assign,readonly) SKUILayoutCache * textLayoutCache;

- (void).cxx_destruct;
- (void)_setActiveMetricsImpressionSession:(id)arg1;
- (void)_setActivePageWidth:(double)arg1;
- (void)_setCollectionView:(id)arg1;
- (void)_setColorScheme:(id)arg1;
- (void)_setDefaultPinningTransitionStyle:(long long)arg1;
- (void)_setLandscapePageWidth:(double)arg1;
- (void)_setLayoutStyle:(long long)arg1;
- (void)_setMetricsController:(id)arg1;
- (void)_setParentViewController:(id)arg1;
- (void)_setPortraitPageWidth:(double)arg1;
- (void)_setResourceLoader:(id)arg1;
- (void)_setTextLayoutCache:(id)arg1;
- (id)activeMetricsImpressionSession;
- (double)activePageWidth;
- (id)clientContext;
- (id)collectionView;
- (id)colorScheme;
- (long long)defaultPinningTransitionStyle;
- (id)init;
- (id)itemOfferButtonAppearance;
- (double)landscapePageWidth;
- (long long)layoutStyle;
- (id)metricsController;
- (id)parentViewController;
- (id)placeholderColor;
- (double)portraitPageWidth;
- (id)resourceLoader;
- (id)textLayoutCache;

@end
