/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDUser : NSObject <NSSecureCoding> {
    HMDHome *_home;
    NSString *_pairingUsername;
    unsigned long long _privilege;
    NSData *_publicKey;
    bool _remoteGateway;
    NSString *_userID;
    NSUUID *_uuid;
}

@property (nonatomic, readonly) HMDHome *home;
@property (nonatomic, readonly, copy) NSString *pairingUsername;
@property (nonatomic, readonly) unsigned long long privilege;
@property (nonatomic, readonly, copy) NSData *publicKey;
@property (getter=isRemoteGateway, nonatomic, readonly) bool remoteGateway;
@property (nonatomic, readonly, copy) NSString *userID;
@property (nonatomic, readonly, copy) NSUUID *uuid;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)home;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 pairingUsername:(id)arg2 publicKey:(id)arg3 privilege:(unsigned long long)arg4 remoteGateway:(bool)arg5 home:(id)arg6;
- (bool)isRemoteGateway;
- (id)lookupDisplayName;
- (id)pairingUsername;
- (unsigned long long)privilege;
- (id)publicKey;
- (id)userID;
- (id)uuid;

@end
