/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEVPNProtocolIKEv2 : NEVPNProtocolIPSec {
    NEVPNIKEv2SecurityAssociationParameters *_IKESecurityAssociationParameters;
    long long _certificateType;
    NEVPNIKEv2SecurityAssociationParameters *_childSecurityAssociationParameters;
    long long _deadPeerDetectionRate;
    NSString *_serverCertificateCommonName;
    NSString *_serverCertificateIssuerCommonName;
    bool _wakeForRekey;
}

@property(assign,readonly) NEVPNIKEv2SecurityAssociationParameters * IKESecurityAssociationParameters;
@property(assign,readwrite) long long certificateType;
@property(assign,readonly) NEVPNIKEv2SecurityAssociationParameters * childSecurityAssociationParameters;
@property(assign,readwrite) long long deadPeerDetectionRate;
@property(assign,copy) NSString * serverCertificateCommonName;
@property(assign,copy) NSString * serverCertificateIssuerCommonName;
@property(assign,readwrite) bool wakeForRekey;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)IKESecurityAssociationParameters;
- (long long)certificateType;
- (bool)checkValidityAndCollectErrors:(id)arg1;
- (id)childSecurityAssociationParameters;
- (id)clone;
- (id)copyLegacyDictionary;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (long long)deadPeerDetectionRate;
- (id)descriptionWithIndent:(int)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)serverCertificateCommonName;
- (id)serverCertificateIssuerCommonName;
- (void)setCertificateType:(long long)arg1;
- (void)setDeadPeerDetectionRate:(long long)arg1;
- (void)setServerCertificateCommonName:(id)arg1;
- (void)setServerCertificateIssuerCommonName:(id)arg1;
- (void)setWakeForRekey:(bool)arg1;
- (bool)wakeForRekey;

@end
