/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface CKDQueryURLRequest : CKDURLRequest {
    NSData *_cursor;
    unsigned long long _limit;
    CKQuery *_query;
    NSMutableArray *_queryResponses;
    NSArray *_requestedFields;
    NSData *_resultsCursor;
    CKRecordZoneID *_zoneID;
}

@property(assign,retain) NSData * cursor;
@property(assign,readwrite) unsigned long long limit;
@property(assign,retain) CKQuery * query;
@property(assign,retain) NSArray * queryResponses;
@property(assign,retain) NSArray * requestedFields;
@property(assign,retain) NSData * resultsCursor;
@property(assign,retain) CKRecordZoneID * zoneID;

- (void).cxx_destruct;
- (bool)allowsAnonymousAccount;
- (id)cursor;
- (id)initWithQuery:(id)arg1 cursor:(id)arg2 limit:(unsigned long long)arg3 requestedFields:(id)arg4 zoneID:(id)arg5;
- (unsigned long long)limit;
- (int)operationType;
- (id)query;
- (id)queryResponses;
- (void)requestDidParseNodeFailure:(id)arg1;
- (id)requestDidParseProtobufObject:(id)arg1;
- (id)requestOperationClasses;
- (id)requestOperations;
- (id)requestedFields;
- (id)resultsCursor;
- (void)setCursor:(id)arg1;
- (void)setLimit:(unsigned long long)arg1;
- (void)setQuery:(id)arg1;
- (void)setQueryResponses:(id)arg1;
- (void)setRequestedFields:(id)arg1;
- (void)setResultsCursor:(id)arg1;
- (void)setZoneID:(id)arg1;
- (id)zoneID;
- (id)zoneIDsToLock;

@end
