/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKTypingView : UIView

@property(assign,retain) CKTypingIndicatorLayer * layer;

+ (Class)layerClass;

@end
