/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUAirplayController : NSObject <MPAVRoutingControllerDelegate> {
    MPAVRoutingController *_airplayDeviceController;
    bool _applicationInBackground;
    NSMutableArray *_availabilityHandlers;
    PUAirplayRoute *_currentRoute;
    NSMutableArray *_currentRouteHandlers;
    PUAirplayRoute *_defaultRoute;
    bool _hasNonDefaultRoute;
    NSMutableDictionary *_knownRoutes;
    id _routeChangeCompletionBlock;
    NSMutableArray *_routeHandlers;
    NSArray *_sortedRoutes;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_broadcastRouteInformation;
- (void)_didEnterBackground:(id)arg1;
- (void)_gatherRouteInformation;
- (void)_updateAirplayDiscoveryMode;
- (void)_updateCurrentRoute;
- (void)_updateFromAVRoute:(id)arg1;
- (void)_updateRouteInformationFromRoutes:(id)arg1;
- (void)_willEnterForeground:(id)arg1;
- (id)currentRoute;
- (id)defaultRoute;
- (id)description;
- (id)init;
- (void)makeRouteCurrent:(id)arg1 completion:(id)arg2;
- (void)requestCurrentRouteUpdatesFor:(id)arg1 handler:(id)arg2;
- (void)requestRouteAvailabilityUpdatesFor:(id)arg1 handler:(id)arg2;
- (void)requestRouteUpdatesFor:(id)arg1 handler:(id)arg2;
- (void)routingController:(id)arg1 didFailToPickRouteWithError:(id)arg2;
- (void)routingControllerAvailableRoutesDidChange:(id)arg1;
- (void)stopCurrentRouteUpdatesFor:(id)arg1;
- (void)stopRouteAvailabilityUpdatesFor:(id)arg1;
- (void)stopRouteUpdatesFor:(id)arg1;

@end
