/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUPhotoEditProtoSettings : PUSettings {
    bool _allowAnyPlugin;
    bool _autoCropEnabled;
    bool _cropMaskBlurred;
    double _cropRecomposeDelay;
    double _cropSideMargins;
    double _cropWheelSize;
    bool _showLevelIndicator;
    bool _showResetToolButton;
    bool _simulateDownload;
    bool _simulateDownloadFailure;
    bool _useOldPhotosEditor2;
}

@property(assign,readwrite) bool allowAnyPlugin;
@property(assign,readwrite) bool autoCropEnabled;
@property(assign,readwrite) bool cropMaskBlurred;
@property(assign,readwrite) double cropRecomposeDelay;
@property(assign,readwrite) double cropSideMargins;
@property(assign,readwrite) double cropWheelSize;
@property(assign,readwrite) bool showLevelIndicator;
@property(assign,readwrite) bool showResetToolButton;
@property(assign,readwrite) bool simulateDownload;
@property(assign,readwrite) bool simulateDownloadFailure;
@property(assign,readwrite) bool useOldPhotosEditor2;

+ (id)settingsControllerModule;
+ (id)sharedInstance;

- (bool)allowAnyPlugin;
- (bool)autoCropEnabled;
- (bool)cropMaskBlurred;
- (double)cropRecomposeDelay;
- (double)cropSideMargins;
- (double)cropWheelSize;
- (void)setAllowAnyPlugin:(bool)arg1;
- (void)setAutoCropEnabled:(bool)arg1;
- (void)setCropMaskBlurred:(bool)arg1;
- (void)setCropRecomposeDelay:(double)arg1;
- (void)setCropSideMargins:(double)arg1;
- (void)setCropWheelSize:(double)arg1;
- (void)setDefaultValues;
- (void)setShowLevelIndicator:(bool)arg1;
- (void)setShowResetToolButton:(bool)arg1;
- (void)setSimulateDownload:(bool)arg1;
- (void)setSimulateDownloadFailure:(bool)arg1;
- (void)setUseOldPhotosEditor2:(bool)arg1;
- (bool)showLevelIndicator;
- (bool)showResetToolButton;
- (bool)simulateDownload;
- (bool)simulateDownloadFailure;
- (bool)useOldPhotosEditor2;

@end
