/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PassKit.framework/PassKit
 */

@interface PKPaymentOptionsViewController : UITableViewController <ABPeoplePickerNavigationControllerDelegate, ABPostalAddressEditorDelegate, UITextFieldDelegate> {
    ABPostalAddressEditorNavigationController *_addressEditorViewController;
    <PKPaymentOptionsViewControllerDelegate> *_delegate;
    bool _isEditable;
    PKPaymentOptionsModel *_optionsModel;
    int _optionsStyle;
    PKPassSnapshotter *_passSnapshotter;
    id _pickedABPersonHandler;
    id _pickedABPropertyHandler;
    bool _showDisclosureIndicators;
    NSString *_title;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <PKPaymentOptionsViewControllerDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,copy) id pickedABPersonHandler;
@property(assign,copy) id pickedABPropertyHandler;
@property(assign,readwrite) bool showDisclosureIndicators;
@property(assign,readonly) Class superclass;

- (id)_passSnapshotter;
- (bool)_presentedModally;
- (void)_showABPickerForPropertyID:(int)arg1 optionsGroup:(id)arg2;
- (void)_showAddressEntryViewControllerForOptionsGroup:(id)arg1;
- (void)_showEntryViewControllerForPropertyID:(int)arg1 optionsGroup:(id)arg2;
- (void)_updateContactName;
- (void)_updateNavigationBar;
- (void)dealloc;
- (id)delegate;
- (id)initWithStyle:(long long)arg1;
- (id)initWithTitle:(id)arg1 optionsStyle:(int)arg2;
- (id)initWithTitle:(id)arg1 optionsStyle:(int)arg2 editable:(bool)arg3;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void*)arg2;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (id)pickedABPersonHandler;
- (id)pickedABPropertyHandler;
- (void)postalAddressEditor:(id)arg1 finishedEditingContact:(id)arg2;
- (void)postalAddressEditor:(id)arg1 finishedEditingProperty:(int)arg2 contact:(id)arg3;
- (void)postalAddressEditorDidCancel:(id)arg1;
- (void)setBillingAddressOptions:(id)arg1 selectedIndex:(long long)arg2 optionsChangedHandler:(id)arg3;
- (void)setDelegate:(id)arg1;
- (void)setEmailOptions:(id)arg1 selectedIndex:(long long)arg2 optionsChangedHandler:(id)arg3;
- (void)setNameOptions:(id)arg1 selectedIndex:(long long)arg2 optionsChangedHandler:(id)arg3;
- (void)setPaymentPassOptions:(id)arg1 selectedIndex:(long long)arg2 optionsChangedHandler:(id)arg3;
- (void)setPhoneOptions:(id)arg1 selectedIndex:(long long)arg2 optionsChangedHandler:(id)arg3;
- (void)setPickedABPersonHandler:(id)arg1;
- (void)setPickedABPropertyHandler:(id)arg1;
- (void)setShippingAddressOptions:(id)arg1 selectedIndex:(long long)arg2 displayMode:(id)arg3 displayName:(id)arg4 optionsChangedHandler:(id)arg5;
- (void)setShippingMethods:(id)arg1 currencyCode:(id)arg2 selectedIndex:(long long)arg3 displayMode:(id)arg4 optionsChangedHandler:(id)arg5;
- (void)setShowDisclosureIndicators:(bool)arg1;
- (bool)showDisclosureIndicators;
- (bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)textFieldDidBeginEditing:(id)arg1;
- (id)title;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;

@end
