/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PassKit.framework/PassKit
 */

@interface PKPaymentShippingContactPresenter : NSObject <PKPaymentAuthorizationViewPresenting>

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

+ (id)_valueForItem:(id)arg1;
+ (void)presentCell:(id)arg1 withDataItem:(id)arg2;

@end
