/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@interface ML3MutableDatabaseTable : ML3DatabaseTable

@property(assign,copy) NSArray * columns;
@property(assign,copy) NSArray * foreignKeyConstraints;
@property(assign,copy) NSString * name;

- (void)setColumns:(id)arg1;
- (void)setForeignKeyConstraints:(id)arg1;
- (void)setName:(id)arg1;

@end
