/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKContactsSearchManager : NSObject <MFContactsSearchConsumer> {
    NSArray *_conversationCache;
    NSNumber *_currentSearchTaskID;
    <CKContactsSearchManagerDelegate> *_delegate;
    NSArray *_enteredRecipients;
    unsigned long long _pendingSearchTypes;
    NSMutableDictionary *_recentsDateMap;
    MFContactsSearchManager *_searchManager;
    MFContactsSearchResultsModel *_searchResultsModel;
    NSString *_searchText;
    bool _suppressGroupSuggestions;
}

@property(assign,copy) NSArray * conversationCache;
@property(assign,retain) NSNumber * currentSearchTaskID;
@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <CKContactsSearchManagerDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,retain) NSArray * enteredRecipients;
@property(assign,readonly) unsigned long long hash;
@property(assign,readwrite) unsigned long long pendingSearchTypes;
@property(assign,retain) NSMutableDictionary * recentsDateMap;
@property(assign,retain) MFContactsSearchManager * searchManager;
@property(assign,retain) MFContactsSearchResultsModel * searchResultsModel;
@property(assign,retain) NSString * searchText;
@property(assign,readonly) Class superclass;
@property(assign,readwrite) bool suppressGroupSuggestions;

- (void)_generateConversationCache;
- (void)_sortSearchResultsWithCoreRecentsResults:(id)arg1 namedSearchResults:(id)arg2;
- (void)beganNetworkActivity;
- (void)cancelSearch;
- (void)chatStateChanged:(id)arg1;
- (void)consumeSearchResults:(id)arg1 type:(unsigned long long)arg2 taskID:(id)arg3;
- (id)conversationCache;
- (id)currentSearchTaskID;
- (void)dealloc;
- (id)delegate;
- (void)endedNetworkActivity;
- (id)enteredRecipients;
- (void)finishedSearchingForType:(unsigned long long)arg1;
- (void)finishedTaskWithID:(id)arg1;
- (id)init;
- (unsigned long long)pendingSearchTypes;
- (id)recentsDateMap;
- (id)searchManager;
- (id)searchResultsModel;
- (id)searchText;
- (void)searchWithText:(id)arg1;
- (void)setConversationCache:(id)arg1;
- (void)setCurrentSearchTaskID:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setEnteredRecipients:(id)arg1;
- (void)setPendingSearchTypes:(unsigned long long)arg1;
- (void)setRecentsDateMap:(id)arg1;
- (void)setSearchManager:(id)arg1;
- (void)setSearchResultsModel:(id)arg1;
- (void)setSearchText:(id)arg1;
- (void)setSuppressGroupSuggestions:(bool)arg1;
- (bool)suppressGroupSuggestions;

@end
