/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKScrollViewController : CKViewController {
    double _bottomInsetPadding;
    bool _keyboardInteractionCancelled;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    } _keyboardScreenFrame;
    bool _keyboardVisible;
    UIScrollView *_scrollView;
    bool _topInsetIncludesPalette;
    double _topInsetPadding;
    IMScheduledUpdater *_updater;
}

@property(assign,readonly) double bottomInsetPadding;
@property(assign,readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } keyboardFrame;
@property(assign,readwrite) bool keyboardInteractionCancelled;
@property(getter=isKeyboardOnscreenWithoutAccessoryView,assign,readonly) bool keyboardOnscreenWithoutAccessoryView;
@property(assign,readwrite) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } keyboardScreenFrame;
@property(getter=isKeyboardUndocked,assign,readonly) bool keyboardUndocked;
@property(getter=isKeyboardVisible,assign,readwrite) bool keyboardVisible;
@property(assign,readonly) UIScrollView * scrollView;
@property(assign,readonly) bool topInsetIncludesPalette;
@property(assign,readonly) double topInsetPadding;
@property(assign,retain) IMScheduledUpdater * updater;

- (double)_bottomRotatingFooterHeight;
- (void)_changedStatusBarFrame:(id)arg1;
- (void)_entryViewWillRotate:(id)arg1;
- (void)_updateScrollGeometryWithDuration:(double)arg1;
- (double)_visibleKeyboardHeight;
- (double)accessoryViewHeight;
- (void)beginHoldingScrollGeometryUpdatesForKey:(id)arg1;
- (double)bottomInsetPadding;
- (double)bottomInsetWithoutAccessoryView;
- (void)contentInsetDidChange;
- (void)contentInsetWillChange:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1 animated:(bool)arg2 duration:(double)arg3;
- (void)dealloc;
- (void)endHoldingScrollGeometryUpdatesForAllKeys;
- (void)endHoldingScrollGeometryUpdatesForKey:(id)arg1;
- (id)init;
- (bool)isKeyboardOnscreenWithoutAccessoryView;
- (bool)isKeyboardUndocked;
- (bool)isKeyboardVisible;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardDidShowOrHide:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })keyboardFrame;
- (bool)keyboardInteractionCancelled;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })keyboardScreenFrame;
- (void)keyboardVisibilityWillChange;
- (void)keyboardWillHideViaGesture;
- (void)keyboardWillShowOrHide:(id)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })navigationBarInsets;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })navigationBarInsetsWithoutPalette;
- (id)scrollView;
- (void)setKeyboardInteractionCancelled:(bool)arg1;
- (void)setKeyboardScreenFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setKeyboardVisible:(bool)arg1;
- (void)setUpdater:(id)arg1;
- (bool)topInsetIncludesPalette;
- (double)topInsetPadding;
- (void)updateScrollGeometry;
- (id)updater;
- (double)visibleHeightAboveKeyboard;

@end
