/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Weather.framework/Weather
 */

@interface WeatherNoContentView : UIView {
    UIView *_centerView;
    struct { 
        double centerLabelHorizontalOffset; 
        double viewSize; 
    } _layout;
}

+ (id)imageWithOptions:(id)arg1 opaque:(bool)arg2 scale:(double)arg3;

- (id)initwithSize:(long long)arg1 centerView:(id)arg2;
- (void)layoutSubviews;

@end
