/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSAccelerometer : NSObject <BKSAccelerometerDelegate> {
    BKSAccelerometer *_bksMirror;
    <SBSAccelerometerDelegate> *_delegate;
}

@property(assign,readwrite) bool accelerometerEventsEnabled;
@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <SBSAccelerometerDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readwrite) bool orientationEventsEnabled;
@property(assign,readonly) Class superclass;
@property(assign,readwrite) double updateInterval;
@property(assign,readwrite) float xThreshold;
@property(assign,readwrite) float yThreshold;
@property(assign,readwrite) float zThreshold;

- (void)accelerometer:(id)arg1 didAccelerateWithTimeStamp:(double)arg2 x:(float)arg3 y:(float)arg4 z:(float)arg5 eventType:(int)arg6;
- (void)accelerometer:(id)arg1 didChangeDeviceOrientation:(int)arg2;
- (bool)accelerometerEventsEnabled;
- (int)currentDeviceOrientation;
- (void)dealloc;
- (id)delegate;
- (id)init;
- (bool)orientationEventsEnabled;
- (void)setAccelerometerEventsEnabled:(bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)setOrientationEventsEnabled:(bool)arg1;
- (void)setUpdateInterval:(double)arg1;
- (void)setXThreshold:(float)arg1;
- (void)setYThreshold:(float)arg1;
- (void)setZThreshold:(float)arg1;
- (double)updateInterval;
- (float)xThreshold;
- (float)yThreshold;
- (float)zThreshold;

@end
