/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Search.framework/Search
 */

@interface SPSearchResultSerializer : NSObject {
    unsigned long long _byteVector;
    unsigned int _byteVectorCapacity;
    unsigned int _byteVectorCnt;
    bool _completed;
    bool _inProc;
    Class _lastResultClass;
    bool _respondsToAuxiliarySubtitleUTF8String;
    bool _respondsToAuxiliaryTitleUTF8String;
    bool _respondsToBadgeValue;
    bool _respondsToIdentifier;
    bool _respondsToSubtitleUTF8String;
    bool _respondsToSummaryUTF8String;
    bool _respondsToTitleUTF8String;
    bool _respondsToURL;
    NSMutableArray *_sections;
}

@property(assign,readonly) bool completed;

- (unsigned long long)_allocateSize:(unsigned long long)arg1;
- (id)_convertConformingResult:(id)arg1;
- (bool)appendResult:(id)arg1;
- (bool)appendSection:(id)arg1;
- (unsigned long long)byteVector;
- (unsigned int)byteVectorCount;
- (bool)completed;
- (void)dealloc;
- (id)init;
- (id)initWithInitialCapacity:(unsigned int)arg1;
- (id)initWithInitialCapacity:(unsigned int)arg1 inProc:(bool)arg2;
- (bool)lockedAppendResult:(id)arg1 toSection:(id)arg2;
- (unsigned long long)sectionCount;
- (void)serialize;
- (void)updateScoesForQuery:(id)arg1 inDomain:(int)arg2;

@end
