/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKDownloadObserver : NSObject <SSDownloadManagerObserver> {
    SSDownloadManager *_downloadManager;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,retain) SSDownloadManager * downloadManager;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

+ (id)sharedObserver;

- (void)dealloc;
- (id)downloadManager;
- (void)downloadManager:(id)arg1 downloadStatesDidChange:(id)arg2;
- (id)init;
- (bool)isDownloadingGame:(id)arg1;
- (void)setDownloadManager:(id)arg1;

@end
