/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKNearbyDevice : NSObject {
    NSString *_deviceID;
    GKDiscovery *_discovery;
    NSDictionary *_pendingInvite;
    GKPlayer *_player;
    long long _state;
}

@property(assign,retain) NSString * deviceID;
@property(assign,retain) GKDiscovery * discovery;
@property(assign,retain) NSDictionary * pendingInvite;
@property(assign,retain) GKPlayer * player;
@property(assign,readwrite) long long state;

+ (id)nearbyDeviceWithID:(id)arg1 discovery:(id)arg2;

- (void)dealloc;
- (id)deviceID;
- (id)discovery;
- (id)pendingInvite;
- (id)player;
- (void)sendDictionary:(id)arg1;
- (void)setDeviceID:(id)arg1;
- (void)setDiscovery:(id)arg1;
- (void)setPendingInvite:(id)arg1;
- (void)setPlayer:(id)arg1;
- (void)setState:(long long)arg1;
- (long long)state;

@end
