/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

@interface CalDAVScheduleCalendarTranspItem : CoreDAVItem {
    CoreDAVItemWithNoChildren *_transparent;
}

@property(assign,readonly) bool isScheduleTransparent;
@property(assign,retain) CoreDAVItemWithNoChildren * transparent;

- (id)copyParseRules;
- (void)dealloc;
- (id)initWithNameSpace:(id)arg1 andName:(id)arg2;
- (bool)isScheduleTransparent;
- (void)setTransparent:(id)arg1;
- (id)transparent;

@end
