/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

@interface CalDAVScheduleTask : CoreDAVPostTask {
    NSArray *_attendees;
    NSString *_originator;
    CalDAVScheduleResponseItem *_scheduleResponse;
}

@property(assign,retain) NSArray * attendees;
@property(assign,retain) NSString * originator;
@property(assign,retain) CalDAVScheduleResponseItem * scheduleResponse;

- (id)additionalHeaderValues;
- (id)attendees;
- (id)copyDefaultParserForContentType:(id)arg1;
- (void)dealloc;
- (void)finishCoreDAVTaskWithError:(id)arg1;
- (id)initWithOriginator:(id)arg1 attendees:(id)arg2 outboxURL:(id)arg3 payload:(id)arg4;
- (id)originator;
- (id)scheduleResponse;
- (void)setAttendees:(id)arg1;
- (void)setOriginator:(id)arg1;
- (void)setScheduleResponse:(id)arg1;

@end
