/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DataAccessExpress.framework/DataAccessExpress
 */

@interface DAContactsSearchQuery : DASearchQuery {
    bool _includePhotos;
    NSString *_searchBase;
    NSString *_searchScope;
}

@property(assign,readwrite) bool includePhotos;
@property(assign,copy) NSString * searchBase;
@property(assign,copy) NSString * searchScope;

+ (id)contactsSearchQueryWithSearchString:(id)arg1 searchBase:(id)arg2 searchScope:(id)arg3 consumer:(id)arg4;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (bool)includePhotos;
- (id)initWithDictionaryRepresentation:(id)arg1 consumer:(id)arg2;
- (id)initWithSearchString:(id)arg1 searchBase:(id)arg2 searchScope:(id)arg3 consumer:(id)arg4;
- (id)searchBase;
- (id)searchScope;
- (void)setIncludePhotos:(bool)arg1;
- (void)setSearchBase:(id)arg1;
- (void)setSearchScope:(id)arg1;

@end
