/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DataAccessExpress.framework/DataAccessExpress
 */

@interface DADisableableObject : NSObject {
    bool _isDisabled;
}

@property(assign,readwrite) bool isDisabled;

- (void)disable;
- (bool)isDisabled;
- (void)setIsDisabled:(bool)arg1;

@end
