/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebUI.framework/WebUI
 */

@interface WBSParsecSearchMoviesResult : WBSParsecSearchResult {
    NSString *_descriptionLeadInText;
    NSMutableArray *_posterRepresentations;
}

@property(assign,readonly) NSString * descriptionLeadInText;

- (void).cxx_destruct;
- (id)descriptionLeadInText;
- (id)initWithDictionary:(id)arg1;
- (id)postersWithSession:(id)arg1;

@end
