/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLCachedImage : UIImage {
    PLLoadRequestKey *_cacheKey;
    int _format;
    NSDictionary *_metadata;
}

@property(assign,copy) PLLoadRequestKey * cacheKey;
@property(assign,readwrite) int format;
@property(assign,retain) NSDictionary * metadata;

- (id)cacheKey;
- (void)dealloc;
- (id)description;
- (int)format;
- (id)metadata;
- (void)setCacheKey:(id)arg1;
- (void)setFormat:(int)arg1;
- (void)setMetadata:(id)arg1;

@end
