/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebUI.framework/WebUI
 */

@interface WBSCloudHistory : NSObject <WBSCloudHistorySyncThrottlerDataStore> {
    bool _cloudHistoryEnabled;
    NSObject<OS_dispatch_queue> *_cloudHistoryQueue;
    WBSCloudHistorySyncThrottler *_fetchChangesThrottler;
    bool _fetchChangesWhenBackoffTimerFires;
    bool _fetchChangesWhenHistoryLoads;
    struct unique_ptr<SafariShared::SuddenTerminationDisabler, std::__1::default_delete<SafariShared::SuddenTerminationDisabler> > { 
        struct __compressed_pair<SafariShared::SuddenTerminationDisabler *, std::__1::default_delete<SafariShared::SuddenTerminationDisabler> > { 
            struct SuddenTerminationDisabler {} *__first_; 
        } __ptr_; 
    } _fetchOperationSuddenTerminationDisabler;
    <NSObject> *_historyWasLoadedObserver;
    unsigned long long _numberOfDevicesInSyncCircle;
    WBSCloudHistoryPushAgentProxy *_pushAgent;
    NSTimer *_pushNotificationFetchTimer;
    bool _removedHistoryItemsArePendingSave;
    WBSCloudHistorySyncThrottler *_saveChangesThrottler;
    bool _saveChangesWhenBackoffTimerFires;
    bool _saveChangesWhenHistoryLoads;
    struct unique_ptr<SafariShared::SuddenTerminationDisabler, std::__1::default_delete<SafariShared::SuddenTerminationDisabler> > { 
        struct __compressed_pair<SafariShared::SuddenTerminationDisabler *, std::__1::default_delete<SafariShared::SuddenTerminationDisabler> > { 
            struct SuddenTerminationDisabler {} *__first_; 
        } __ptr_; 
    } _saveOperationSuddenTerminationDisabler;
    NSTimer *_serverBackoffTimer;
    NSMutableDictionary *_syncCircleSizeRetrievalCompletionHandlersByOperation;
    WBSCloudHistorySyncThrottler *_syncCircleSizeRetrievalThrottler;
}

@property (getter=isCloudHistoryEnabled, nonatomic) bool cloudHistoryEnabled;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long numberOfDevicesInSyncCircle;
@property (readonly) Class superclass;

+ (id)sharedCloudHistory;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_backOffWithInterval:(double)arg1;
- (double)_backoffTimeIntervalFromError:(id)arg1;
- (unsigned long long)_cachedNumberOfDevicesInSyncCircle;
- (void)_cloudHistoryConfigurationChanged:(id)arg1;
- (id)_currentFetchChangesThrottlerPolicyString;
- (id)_currentSyncCircleSizeRetrievalThrottlerPolicyString;
- (void)_determineNumberOfDevicesInSyncCircleForOperation:(id)arg1 completionHandler:(id)arg2;
- (long long)_estimatedPriorityForPotentialSaveAttempt;
- (void)_fetchAndMergeChangesBypassingThrottler:(bool)arg1;
- (void)_fetchAndMergeChangesWithServerChangeTokenData:(id)arg1 intoHistory:(id)arg2 withPriority:(long long)arg3;
- (void)_fetchChangesInResponseToPushNotification:(id)arg1;
- (void)_fetchChangesWhenHistoryLoads;
- (void)_historyItemsWereRemoved:(id)arg1;
- (void)_historyWasLoaded:(id)arg1;
- (void)_initializePushNotificationSupport;
- (void)_performBlockAsynchronouslyOnCloudHistoryQueueAfterHistoryHasLoaded:(id)arg1;
- (void)_postSaveChangesAttemptCompletedNotificationWithAllPendingDataSaved:(bool)arg1;
- (long long)_priorityForSaveWithVisits:(id)arg1 tombstones:(id)arg2 bypassingThrottler:(bool)arg3;
- (void)_processPendingPushNotifications;
- (void)_pushNotificationReceived:(id)arg1;
- (void)_registerForHistoryWasLoadedNotificationIfNecessary;
- (long long)_resultFromError:(id)arg1;
- (void)_saveChangesToCloudHistoryStoreBypassingThrottler:(bool)arg1;
- (void)_saveChangesWhenHistoryLoads;
- (void)_saveVisits:(id)arg1 tombstones:(id)arg2 toCloudHistoryBypassingThrottler:(bool)arg3 withCallback:(id)arg4;
- (void)_serverBackoffTimerFired:(id)arg1;
- (void)_setCachedNumberOfDevicesInSyncCircle:(unsigned long long)arg1;
- (void)_updateDeviceCountInResponseToPushNotification;
- (void)_updateFetchThrottlerAndSaveThrottlerPolicies;
- (id)currentSaveChangesThrottlerPolicyString;
- (id)dateOfNextPermittedSaveChangesAttempt;
- (void)dealloc;
- (void)fetchAndMergeChanges;
- (void)fetchAndMergeChangesBypassingThrottler;
- (id)init;
- (bool)isCloudHistoryEnabled;
- (unsigned long long)numberOfDevicesInSyncCircle;
- (id)recordOfPastOperationsForThrottler:(id)arg1;
- (void)resetForAccountChange;
- (void)saveChangesToCloudHistoryStore;
- (void)saveChangesToCloudHistoryStoreBypassingThrottler;
- (void)setCloudHistoryEnabled:(bool)arg1;
- (void)setNumberOfDevicesInSyncCircle:(unsigned long long)arg1;
- (void)setRecordOfPastOperations:(id)arg1 forThrottler:(id)arg2;

@end
