/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface _SKUIItemBrowseCellContentView : UIView {
    UILabel *_indexNumberLabel;
    UILabel *_subtitleLabel;
    UILabel *_titleLabel;
    SKUICellImageView *_userRatingImageView;
    UILabel *_userRatingLabel;
}

@property(assign,retain) UILabel * indexNumberLabel;
@property(assign,retain) UILabel * subtitleLabel;
@property(assign,retain) UILabel * titleLabel;
@property(assign,retain) SKUICellImageView * userRatingImageView;
@property(assign,retain) UILabel * userRatingLabel;

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)indexNumberLabel;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setIndexNumberLabel:(id)arg1;
- (void)setSubtitleLabel:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (void)setUserRatingImageView:(id)arg1;
- (void)setUserRatingLabel:(id)arg1;
- (id)subtitleLabel;
- (id)titleLabel;
- (id)userRatingImageView;
- (id)userRatingLabel;

@end
