/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIJSAppleAccount : NSObject <SKUIJSAppleAccount> {
    ACAccount *_account;
    ACAccount *_nativeAccount;
}

@property(assign,readonly) NSString * DSID;
@property(assign,readonly) NSString * accountDescription;
@property(assign,readonly) NSString * identifier;
@property(assign,readonly) ACAccount * nativeAccount;
@property(assign,readonly) NSString * username;

- (void).cxx_destruct;
- (id)DSID;
- (id)accountDescription;
- (id)identifier;
- (id)initWithACAccount:(id)arg1;
- (id)nativeAccount;
- (id)username;

@end
