/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIProductPagePlaceholderViewController : UIViewController <SKUIProductPageChildViewController, UIScrollViewDelegate> {
    SKUIClientContext *_clientContext;
    SKUIColorScheme *_colorScheme;
    <SKUIProductPageChildViewControllerDelegate> *_delegate;
    SKUIProductPageHeaderViewController *_headerViewController;
    UIActivityIndicatorView *_indicator;
    SKUIProductPagePlaceholderScrollView *_scrollView;
    long long _style;
}

@property(assign,retain) SKUIClientContext * clientContext;
@property(assign,retain) SKUIColorScheme * colorScheme;
@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <SKUIProductPageChildViewControllerDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,retain) SKUIProductPageHeaderViewController * headerViewController;
@property(assign,readonly) UIScrollView * scrollView;
@property(assign,readonly) Class superclass;

- (void).cxx_destruct;
- (void)_addHeaderView;
- (id)clientContext;
- (id)colorScheme;
- (id)delegate;
- (id)headerViewController;
- (id)initWithStyle:(long long)arg1;
- (void)loadView;
- (id)scrollView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setClientContext:(id)arg1;
- (void)setColorScheme:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setHeaderViewController:(id)arg1;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;

@end
