/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIClientContext : NSObject <SUClientInterfaceDelegatePrivate> {
    NSString *_additionalPurchaseParameters;
    SKUIApplicationController *_applicationController;
    NSBundle *_bundle;
    SUClientInterface *_clientInterface;
    NSDictionary *_configurationDictionary;
    SKUIStoreDialogController *_dialogController;
    SKUILocalizedStringDictionary *_localizedStrings;
    NSString *_metricsConfigurationIdentifier;
    NSMapTable *_metricsPageContexts;
    NSMutableArray *_navigationHistory;
    NSString *_navigationHistoryPersistenceKey;
    NSString *_purchaseAffiliateIdentifier;
    SKUIURL *_purchaseReferrerURL;
    long long _purchaseURLBagType;
    SSVFairPlaySAPSession *_sapSessionDefault;
    SSVFairPlaySAPSession *_sapSessionPrime;
    IKAppContext *_scriptAppContext;
    NSString *_storeFrontIdentifier;
    SSUpdatableAssetController *_updatableAssetController;
    SKUIURLBag *_urlBag;
    long long _userInterfaceIdiomOverride;
}

@property(assign,readonly) SSURLBag * URLBag;
@property(getter=_applicationController,setter=_setApplicationController:,assign,readwrite) SKUIApplicationController * _applicationController;
@property(getter=_scriptAppContext,setter=_setScriptAppContext:,assign,retain) IKAppContext * _scriptAppContext;
@property(assign,readonly) SUClientInterface * clientInterface;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,copy) NSString * metricsConfigurationIdentifier;
@property(assign,readonly) NSArray * navigationHistory;
@property(assign,copy) NSString * navigationHistoryPersistenceKey;
@property(assign,readonly) SSVPlatformContext * platformContext;
@property(assign,copy) SKUIURL * purchaseReferrerURL;
@property(assign,readonly) NSString * storeFrontIdentifier;
@property(assign,readonly) Class superclass;
@property(assign,retain) SSUpdatableAssetController * updatableAssetController;
@property(assign,readwrite) long long userInterfaceIdiomOverride;

+ (id)_cachePathForStoreFrontIdentifier:(id)arg1;
+ (id)_configurationDictionaryWithBagDictionary:(id)arg1;
+ (id)defaultContext;

- (void).cxx_destruct;
- (id)SAPSessionForVersion:(long long)arg1;
- (id)URLBag;
- (id)_applicationController;
- (id)_navigationHistory;
- (id)_scriptAppContext;
- (void)_setAdditionalPurchaseParameters:(id)arg1;
- (void)_setApplicationController:(id)arg1;
- (void)_setPurchaseAffiliateIdentifier:(id)arg1;
- (void)_setPurchaseURLBagType:(long long)arg1;
- (void)_setScriptAppContext:(id)arg1;
- (void)_setValue:(id)arg1 forConfigurationKey:(id)arg2;
- (id)additionalLeftBarButtonItemForDocumentContainerViewController:(id)arg1;
- (id)additionalRightBarButtonItemForDocumentContainerViewController:(id)arg1;
- (id)clientInterface;
- (void)clientInterface:(id)arg1 dispatchOnPageResponseWithData:(id)arg2 response:(id)arg3;
- (void)clientInterface:(id)arg1 dispatchXEvent:(id)arg2 completionBlock:(id)arg3;
- (void)clientInterface:(id)arg1 presentDialog:(id)arg2;
- (void)customizePurchase:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)documentViewControllerForTemplateViewElement:(id)arg1;
- (void)getDefaultMetricsControllerWithCompletionBlock:(id)arg1;
- (id)initWithConfigurationDictionary:(id)arg1;
- (void)loadValueForConfigurationKey:(id)arg1 completionBlock:(id)arg2;
- (id)localizedAlertWithError:(id)arg1;
- (id)localizedStringForKey:(id)arg1;
- (id)localizedStringForKey:(id)arg1 inTable:(id)arg2;
- (id)metricsConfigurationIdentifier;
- (id)metricsPageContextForViewController:(id)arg1;
- (id)modalDocumentViewControllerForDocument:(id)arg1 options:(id)arg2;
- (id)navigationHistory;
- (id)navigationHistoryPersistenceKey;
- (id)newLegacyStorePageViewControllerForURLResponse:(id)arg1;
- (id)newLoadStoreURLOperationWithURL:(id)arg1;
- (id)newLoadStoreURLOperationWithURLRequest:(id)arg1;
- (id)platformContext;
- (id)purchaseReferrerURL;
- (void)pushNavigationHistoryPageIdentifier:(id)arg1;
- (id)scriptInterfaceForClientInterface:(id)arg1;
- (void)sendOnPageResponseWithDocument:(id)arg1 data:(id)arg2 URLResponse:(id)arg3 performanceMetrics:(id)arg4;
- (void)sendOnXEventWithDictionary:(id)arg1 completionBlock:(id)arg2;
- (void)setMetricsConfigurationIdentifier:(id)arg1;
- (void)setMetricsPageContext:(id)arg1 forViewController:(id)arg2;
- (void)setNavigationHistoryPersistenceKey:(id)arg1;
- (void)setPurchaseReferrerURL:(id)arg1;
- (void)setUpdatableAssetController:(id)arg1;
- (void)setUserInterfaceIdiomOverride:(long long)arg1;
- (id)storeFrontIdentifier;
- (bool)supportsRenderingVersion:(unsigned int)arg1;
- (id)tabBarItemsForStyle:(long long)arg1;
- (id)updatableAssetController;
- (long long)userInterfaceIdiomOverride;
- (id)valueForConfigurationKey:(id)arg1;

@end
