/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUITrendingSearchTemplateElement : SKUIViewElement

@property(assign,readonly) NSArray * buttons;
@property(assign,readonly) SKUILabelViewElement * titleLabel;

- (id)buttons;
- (id)titleLabel;

@end
