/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIAttributedStringLayout : NSObject <SKUICachedLayout> {
    NSAttributedString *_attributedString;
    struct CGSize { 
        double width; 
        double height; 
    } _boundingSize;
    NSStringDrawingContext *_context;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _edgeInsetsForShadow;
    double _topInset;
    bool _usesTallCharacterSet;
}

@property(assign,readonly) NSAttributedString * attributedString;
@property(assign,readonly) double baselineOffset;
@property(assign,readonly) struct CGSize { double x1; double x2; } boundingSize;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } edgeInsetsForShadow;
@property(assign,readonly) double firstBaselineOffset;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) long long numberOfLines;
@property(assign,readonly) NSStringDrawingContext * stringDrawingContext;
@property(assign,readonly) Class superclass;
@property(assign,readonly) double topInset;
@property(assign,readonly) bool usesTallCharacterSet;

- (void).cxx_destruct;
- (id)attributedString;
- (double)baselineOffset;
- (struct CGSize { double x1; double x2; })boundingSize;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })edgeInsetsForShadow;
- (double)firstBaselineOffset;
- (id)initWithLayoutRequest:(id)arg1;
- (long long)numberOfLines;
- (id)stringDrawingContext;
- (double)topInset;
- (bool)usesTallCharacterSet;

@end
