/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@interface GKRemoteUIHeaderView : UIView <RemoteUITableHeader> {
    double _bottomMargin;
    double _height;
    bool _isFirstSection;
    GKLabel *_textLabel;
}

@property(assign,readwrite) double bottomMargin;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readwrite) double height;
@property(assign,readwrite) bool isFirstSection;
@property(assign,readonly) Class superclass;
@property(assign,retain) GKLabel * textLabel;

- (double)bottomMargin;
- (void)dealloc;
- (double)headerHeightForWidth:(double)arg1 inTableView:(id)arg2;
- (double)height;
- (id)initWithAttributes:(id)arg1;
- (bool)isFirstSection;
- (void)setBottomMargin:(double)arg1;
- (void)setHeight:(double)arg1;
- (void)setIsFirstSection:(bool)arg1;
- (void)setSectionIsFirst:(bool)arg1;
- (void)setTextLabel:(id)arg1;
- (id)textLabel;

@end
