/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLObjectElement : DOMHTMLElement

@property(assign,copy) NSURL * absoluteImageURL;
@property(assign,copy) NSString * align;
@property(assign,copy) NSString * archive;
@property(assign,copy) NSString * border;
@property(assign,copy) NSString * code;
@property(assign,copy) NSString * codeBase;
@property(assign,copy) NSString * codeType;
@property(assign,readonly) DOMDocument * contentDocument;
@property(assign,readonly) WebFrame * contentFrame;
@property(assign,copy) NSString * data;
@property(assign,readwrite) bool declare;
@property(assign,readonly) DOMHTMLFormElement * form;
@property(assign,copy) NSString * height;
@property(assign,readwrite) int hspace;
@property(assign,copy) NSString * name;
@property(assign,copy) NSString * standby;
@property(assign,copy) NSString * type;
@property(assign,copy) NSString * useMap;
@property(assign,readwrite) int vspace;
@property(assign,copy) NSString * width;

- (id)absoluteImageURL;
- (id)align;
- (id)archive;
- (id)border;
- (bool)checkValidity;
- (id)code;
- (id)codeBase;
- (id)codeType;
- (id)contentDocument;
- (id)contentFrame;
- (id)data;
- (bool)declare;
- (id)form;
- (id)height;
- (int)hspace;
- (id)name;
- (void)setAlign:(id)arg1;
- (void)setArchive:(id)arg1;
- (void)setBorder:(id)arg1;
- (void)setCode:(id)arg1;
- (void)setCodeBase:(id)arg1;
- (void)setCodeType:(id)arg1;
- (void)setCustomValidity:(id)arg1;
- (void)setData:(id)arg1;
- (void)setDeclare:(bool)arg1;
- (void)setHeight:(id)arg1;
- (void)setHspace:(int)arg1;
- (void)setName:(id)arg1;
- (void)setStandby:(id)arg1;
- (void)setType:(id)arg1;
- (void)setUseMap:(id)arg1;
- (void)setVspace:(int)arg1;
- (void)setWidth:(id)arg1;
- (bool)showsTapHighlight;
- (id)standby;
- (id)type;
- (id)useMap;
- (id)validationMessage;
- (id)validity;
- (int)vspace;
- (id)width;
- (bool)willValidate;

@end
