/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSXPCConnectionRequestedReplyInfo : NSObject {
    id _cleanupBlock;
    NSProgress *_progress;
}

@property(assign,copy) id cleanupBlock;
@property(assign,retain) NSProgress * progress;

- (id)cleanupBlock;
- (void)dealloc;
- (id)progress;
- (void)setCleanupBlock:(id)arg1;
- (void)setProgress:(id)arg1;

@end
