/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSOperation : NSObject {
    id _private;
    int _private1;
    int _private1b;
}

@property(getter=isAsynchronous,assign,readonly) bool asynchronous;
@property(getter=isCancelled,assign,readonly) bool cancelled;
@property(assign,copy) id completionBlock;
@property(getter=isConcurrent,assign,readonly) bool concurrent;
@property(assign,copy) NSArray * dependencies;
@property(getter=isExecuting,assign,readonly) bool executing;
@property(getter=isFinished,assign,readonly) bool finished;
@property(assign,copy) NSString * name;
@property(assign,readwrite) long long qualityOfService;
@property(assign,readwrite) long long queuePriority;
@property(getter=isReady,assign,readonly) bool ready;
@property(assign,readwrite) unsigned long long tag;
@property(assign,readwrite) double threadPriority;

+ (bool)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)currentOperation;

- (id)__;
- (id)_activity;
- (long long)_effQoS;
- (id)_implicitObservationInfo;
- (void)addDependency:(id)arg1;
- (void)cancel;
- (id)completionBlock;
- (void)dealloc;
- (id)dependencies;
- (id)description;
- (void)finalize;
- (id)init;
- (bool)isAsynchronous;
- (bool)isCancelled;
- (bool)isConcurrent;
- (bool)isExecuting;
- (bool)isFinished;
- (bool)isReady;
- (void)main;
- (id)name;
- (void*)observationInfo;
- (long long)qualityOfService;
- (long long)queuePriority;
- (void)removeDependency:(id)arg1;
- (void)setCompletionBlock:(id)arg1;
- (void)setName:(id)arg1;
- (void)setObservationInfo:(void*)arg1;
- (void)setQualityOfService:(long long)arg1;
- (void)setQueuePriority:(long long)arg1;
- (void)setTag:(unsigned long long)arg1;
- (void)setThreadPriority:(double)arg1;
- (void)start;
- (unsigned long long)tag;
- (double)threadPriority;
- (void)waitUntilFinished;
- (void)waitUntilFinishedOrTimeout:(double)arg1;

@end
