/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIColorBalance : CIFilter {
    CIColor *inputColor;
    NSNumber *inputDamping;
    CIImage *inputImage;
    NSNumber *inputStrength;
    NSNumber *inputWarmth;
}

@property(assign,retain) CIColor * inputColor;
@property(assign,retain) NSNumber * inputDamping;
@property(assign,retain) CIImage * inputImage;
@property(assign,retain) NSNumber * inputStrength;
@property(assign,retain) NSNumber * inputWarmth;

+ (id)customAttributes;

- (id)_kernel;
- (id)inputColor;
- (id)inputDamping;
- (id)inputImage;
- (id)inputStrength;
- (id)inputWarmth;
- (id)outputImage;
- (void)setDefaults;
- (void)setInputColor:(id)arg1;
- (void)setInputDamping:(id)arg1;
- (void)setInputImage:(id)arg1;
- (void)setInputStrength:(id)arg1;
- (void)setInputWarmth:(id)arg1;

@end
