/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBApplicationProcessExitContext : NSObject {
    unsigned long long _exitReason;
    unsigned long long _launchdExitReason;
    FBProcessState *_stateBeforeExiting;
    long long _terminationReason;
}

@property(assign,readonly) int exitCode;
@property(assign,readonly) unsigned long long exitReason;
@property(assign,readonly) long long exitStatus;
@property(assign,readonly) bool exitedNormally;
@property(assign,copy) FBProcessState * stateBeforeExiting;
@property(assign,readonly) long long terminationReason;
@property(assign,readonly) int terminationSignal;

+ (id)descriptionForExitReason:(unsigned long long)arg1;
+ (unsigned long long)exitReasonForLaunchdExitReason:(unsigned long long)arg1;

- (bool)consideredJetsam;
- (void)dealloc;
- (id)description;
- (int)exitCode;
- (unsigned long long)exitReason;
- (long long)exitStatus;
- (bool)exitedNormally;
- (bool)fairPlayFailure;
- (id)initWithExitReason:(unsigned long long)arg1 terminationReason:(long long)arg2 state:(id)arg3;
- (id)stateBeforeExiting;
- (long long)terminationReason;
- (int)terminationSignal;

@end
