/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBWindowContextHostWrapperView : UIView <FBWindowContextAppearance> {
    unsigned long long _appearanceStyle;
    UIColor *_backgroundColorWhileHosting;
    UIColor *_backgroundColorWhileNotHosting;
    FBWindowContextHostManager *_manager;
}

@property(assign,readwrite) unsigned long long appearanceStyle;
@property(assign,retain) UIColor * backgroundColorWhileHosting;
@property(assign,retain) UIColor * backgroundColorWhileNotHosting;
@property(getter=isContextHosted,assign,readonly) bool contextHosted;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) double level;
@property(assign,readonly) FBWindowContextHostManager * manager;
@property(assign,readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } referenceFrame;
@property(assign,readonly) Class superclass;

- (id)_backgroundColorWhileHosting;
- (id)_backgroundColorWhileNotHosting;
- (void)_didRemoveSubview:(id)arg1;
- (id)_hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2 windowServerHitTestWindow:(id)arg3;
- (void)_hostingStatusChanged;
- (bool)_isReallyHosting;
- (void)_setAppearanceStyle:(unsigned long long)arg1 force:(bool)arg2;
- (id)_stringForAppearanceStyle;
- (void)_toggleBackgroundColorIfNecessary;
- (unsigned long long)appearanceStyle;
- (id)backgroundColorWhileHosting;
- (id)backgroundColorWhileNotHosting;
- (void)clearManager;
- (void)dealloc;
- (id)description;
- (void)didAddSubview:(id)arg1;
- (id)initWithHostManager:(id)arg1;
- (bool)isContextHosted;
- (double)level;
- (id)manager;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })referenceFrame;
- (void)setAppearanceStyle:(unsigned long long)arg1;
- (void)setBackgroundColorWhileHosting:(id)arg1;
- (void)setBackgroundColorWhileNotHosting:(id)arg1;
- (void)updateBackgroundColor;
- (void)updateFrame;
- (id)window;

@end
