/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RadioUI.framework/RadioUI
 */

@interface RUHistoryTableViewCell : RUTableViewCell <RUTrackDownloadViewDelegate> {
    RUAudioPreviewView *_audioPreviewView;
    UIImageView *_explicitImageView;
    bool _explicitTrack;
    bool _hideArtworkImage;
    UILabel *_iAdLabel;
    UILabel *_subtitleLabel;
    UILabel *_titleLabel;
    RUTrackDownloadView *_trackDownloadView;
}

@property(assign,copy) NSString * artist;
@property(assign,readonly) UIImage * artworkImage;
@property(assign,retain) RUAudioPreviewView * audioPreviewView;
@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(getter=isExplicitTrack,assign,readwrite) bool explicitTrack;
@property(assign,readonly) unsigned long long hash;
@property(assign,readwrite) bool hideArtworkImage;
@property(assign,readwrite) bool isAd;
@property(assign,readonly) Class superclass;
@property(assign,copy) NSString * title;
@property(assign,readonly) RUTrackDownloadView * trackDownloadView;

+ (id)_iAdLabelFont;
+ (id)_subtitleLabelFontForTraitCollection:(id)arg1;
+ (id)_titleLabelFont;
+ (struct CGSize { double x1; double x2; })artworkSize;
+ (double)defaultHeightForTraitCollection:(id)arg1;

- (void).cxx_destruct;
- (void)_contentSizeCategoryDidChangeNotification:(id)arg1;
- (unsigned long long)_preferredExplicitGlyphSizeCategory;
- (void)_updateViewForHorizontalSizeClassChange;
- (id)artist;
- (id)artworkImage;
- (id)audioPreviewView;
- (void)dealloc;
- (void)didMoveToSuperview;
- (bool)hideArtworkImage;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (bool)isAd;
- (bool)isExplicitTrack;
- (void)layoutSubviews;
- (void)setArtist:(id)arg1;
- (void)setAudioPreviewView:(id)arg1;
- (void)setExplicitTrack:(bool)arg1;
- (void)setHideArtworkImage:(bool)arg1;
- (void)setIsAd:(bool)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
- (id)trackDownloadView;
- (void)trackDownloadViewWillTransition:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;

@end
