/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLPreElement : DOMHTMLElement

@property(assign,readwrite) int width;
@property(assign,readwrite) bool wrap;

- (void)setWidth:(int)arg1;
- (void)setWrap:(bool)arg1;
- (int)width;
- (bool)wrap;

@end
