/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLOptGroupElement : DOMHTMLElement

@property(assign,readwrite) bool disabled;
@property(assign,copy) NSString * label;

- (id)createPickerCell;
- (id)createSelectedItem;
- (bool)disabled;
- (id)itemTitle;
- (id)label;
- (void)populateCell:(id)arg1;
- (void)setDisabled:(bool)arg1;
- (void)setLabel:(id)arg1;

@end
