/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebPolicyDecisionListener : NSObject <WebPolicyDecisionListener> {
    WebPolicyDecisionListenerPrivate *_private;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

- (id)_initWithTarget:(id)arg1 action:(SEL)arg2;
- (void)_invalidate;
- (void)_usePolicy:(int)arg1;
- (void)dealloc;
- (void)download;
- (void)ignore;
- (void)use;

@end
