/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSSystemApplication : NSObject <BKSSystemApplicationClientDelegate> {
    BKSSystemApplicationClient *_client;
    <BKSSystemApplicationDelegate> *_delegate;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <BKSSystemApplicationDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

- (bool)clientIsAliveForWatchdog:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (id)initWithQueue:(id)arg1;
- (void)restart;
- (void)sendActions:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)start;

@end
