/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@interface LSBundleProxy : LSResourceProxy {
    NSURL *_appStoreReceiptURL;
    NSString *_bundleExecutable;
    unsigned long long _bundleFlags;
    NSString *_bundleType;
    NSURL *_bundleURL;
    NSString *_bundleVersion;
    NSUUID *_cacheGUID;
    NSDictionary *_entitlements;
    NSDictionary *_environmentVariables;
    bool _foundBackingBundle;
    NSDictionary *_groupContainerURLs;
    NSString *_localizedShortName;
    NSArray *_machOUUIDs;
    unsigned long long _plistContentFlags;
    unsigned long long _sequenceNumber;
    NSString *_signerIdentity;
}

@property(assign,readonly) NSURL * appStoreReceiptURL;
@property(assign,readonly) NSURL * bundleContainerURL;
@property(assign,readonly) NSString * bundleExecutable;
@property(assign,readonly) NSString * bundleIdentifier;
@property(assign,readonly) NSString * bundleType;
@property(assign,readonly) NSURL * bundleURL;
@property(assign,readonly) NSString * bundleVersion;
@property(assign,readonly) NSUUID * cacheGUID;
@property(assign,readonly) NSURL * containerURL;
@property(assign,readonly) NSURL * dataContainerURL;
@property(assign,readonly) NSDictionary * entitlements;
@property(assign,readonly) NSDictionary * environmentVariables;
@property(assign,readonly) bool foundBackingBundle;
@property(assign,readonly) NSDictionary * groupContainerURLs;
@property(assign,readonly) NSString * localizedShortName;
@property(assign,readonly) NSArray * machOUUIDs;
@property(assign,readonly) unsigned long long sequenceNumber;
@property(assign,readonly) NSString * signerIdentity;

+ (id)bundleProxyForIdentifier:(id)arg1;
+ (id)bundleProxyForURL:(id)arg1;

- (unsigned char)_createContext:(struct LSContext { struct LSDatabase {} *x1; }*)arg1 andGetBundle:(unsigned int*)arg2 withData:(const struct LSBundleData {}**)arg3;
- (id)_initWithBundleUnit:(unsigned int)arg1 bundleType:(unsigned long long)arg2 BundleID:(id)arg3 localizedName:(id)arg4 bundleContainerURL:(id)arg5 dataContainerURL:(id)arg6 resourcesDirectoryURL:(id)arg7 iconsDictionary:(id)arg8 iconFileNames:(id)arg9 version:(id)arg10;
- (id)_plistValueForKey:(id)arg1;
- (id)appStoreReceiptURL;
- (id)bundleContainerURL;
- (id)bundleExecutable;
- (id)bundleIdentifier;
- (id)bundleType;
- (id)bundleURL;
- (id)bundleVersion;
- (id)cacheGUID;
- (id)containerURL;
- (id)dataContainerURL;
- (void)dealloc;
- (id)entitlements;
- (id)environmentVariables;
- (bool)foundBackingBundle;
- (id)groupContainerURLs;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)localizedShortName;
- (id)machOUUIDs;
- (unsigned long long)sequenceNumber;
- (void)setLocalizedShortName:(id)arg1;
- (id)signerIdentity;

@end
