/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@interface BRCPeriodicSyncOperation : _BRCOperation <BRCOperationSubclass> {
    CKServerChangeToken *_metadataChangeToken;
    BRCContainerScheduler *_scheduler;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) CKServerChangeToken * metadataChangeToken;
@property(assign,readonly) BRCContainerScheduler * scheduler;
@property(assign,readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithContainerScheduler:(id)arg1 metadataChangeToken:(id)arg2;
- (void)main;
- (id)metadataChangeToken;
- (id)scheduler;
- (bool)shouldRetryForError:(id)arg1;

@end
