/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@interface BRFieldPkgItem : PBCodable <NSCopying> {
    struct { 
        unsigned int mtime : 1; 
        unsigned int isExecutable : 1; 
        unsigned int isWritable : 1; 
    } _has;
    bool _isExecutable;
    bool _isWritable;
    long long _mtime;
    NSString *_path;
    NSData *_quarantineInfo;
    NSData *_signature;
    NSString *_symlinkContent;
    int _type;
}

@property(assign,readwrite) bool hasIsExecutable;
@property(assign,readwrite) bool hasIsWritable;
@property(assign,readwrite) bool hasMtime;
@property(assign,readonly) bool hasPath;
@property(assign,readonly) bool hasQuarantineInfo;
@property(assign,readonly) bool hasSignature;
@property(assign,readonly) bool hasSymlinkContent;
@property(assign,readwrite) bool isExecutable;
@property(assign,readwrite) bool isWritable;
@property(assign,readwrite) long long mtime;
@property(assign,retain) NSString * path;
@property(assign,retain) NSData * quarantineInfo;
@property(assign,retain) NSData * signature;
@property(assign,retain) NSString * symlinkContent;
@property(assign,readwrite) int type;

- (void).cxx_destruct;
- (void)clear;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasIsExecutable;
- (bool)hasIsWritable;
- (bool)hasMtime;
- (bool)hasPath;
- (bool)hasQuarantineInfo;
- (bool)hasSignature;
- (bool)hasSymlinkContent;
- (unsigned long long)hash;
- (id)initWithPkgItem:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isExecutable;
- (bool)isWritable;
- (void)mergeFrom:(id)arg1;
- (long long)mtime;
- (id)path;
- (id)quarantineInfo;
- (bool)readFrom:(id)arg1;
- (void)setHasIsExecutable:(bool)arg1;
- (void)setHasIsWritable:(bool)arg1;
- (void)setHasMtime:(bool)arg1;
- (void)setIsExecutable:(bool)arg1;
- (void)setIsWritable:(bool)arg1;
- (void)setMtime:(long long)arg1;
- (void)setPath:(id)arg1;
- (void)setQuarantineInfo:(id)arg1;
- (void)setSignature:(id)arg1;
- (void)setSymlinkContent:(id)arg1;
- (void)setType:(int)arg1;
- (id)signature;
- (id)symlinkContent;
- (int)type;
- (void)updateWithPkgItem:(id)arg1;
- (void)writeTo:(id)arg1;

@end
