/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
 */

@interface MPUExtrasActivityIndicatorElementViewController : MPUExtrasViewElementViewController {
    MPUExtrasActivityIndicator *_activityView;
}

- (void).cxx_destruct;
- (void)_prepareLayout;
- (bool)matchParentHeight;
- (void)viewDidLoad;

@end
