/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
 */

@interface MPUExtrasGridViewControllerStyle : NSObject {
    bool _adjustsContentInsetByBottomNavBar;
    UIColor *_backgroundColor;
    double _cellLineSpacing;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _collectionViewInsets;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _defaultCellSectionInsets;
    MPUExtrasGridCellStyle *_defaultCellStyle;
    double _defaultSpacing;
    NSDictionary *_detailDefaultFontAttributes;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _detailInsets;
    UIColor *_detailTextColor;
    NSString *_detailTextStyle;
    MPUExtrasGridHeaderStyle *_headerStyle;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _imageCellSectionInsets;
    MPUExtrasGridCellStyle *_imageCellStyle;
    double _imageSpacing;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _productCellSectionInsets;
    MPUExtrasGridCellStyle *_productCellStyle;
    double _productSpacing;
    MPUExtrasGridSectionHeaderStyle *_sectionHeaderStyle;
    bool _showsScrollFade;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _videoCellSectionInsets;
    MPUExtrasGridCellStyle *_videoCellStyle;
    double _videoSpacing;
}

@property(assign,readwrite) bool adjustsContentInsetByBottomNavBar;
@property(assign,retain) UIColor * backgroundColor;
@property(assign,readwrite) double cellLineSpacing;
@property(assign,readwrite) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } collectionViewInsets;
@property(assign,readwrite) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } defaultCellSectionInsets;
@property(assign,retain) MPUExtrasGridCellStyle * defaultCellStyle;
@property(assign,readwrite) double defaultSpacing;
@property(assign,retain) NSDictionary * detailDefaultFontAttributes;
@property(assign,readwrite) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } detailInsets;
@property(assign,retain) UIColor * detailTextColor;
@property(assign,retain) NSString * detailTextStyle;
@property(assign,retain) MPUExtrasGridHeaderStyle * headerStyle;
@property(assign,readwrite) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } imageCellSectionInsets;
@property(assign,retain) MPUExtrasGridCellStyle * imageCellStyle;
@property(assign,readwrite) double imageSpacing;
@property(assign,readwrite) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } productCellSectionInsets;
@property(assign,retain) MPUExtrasGridCellStyle * productCellStyle;
@property(assign,readwrite) double productSpacing;
@property(assign,retain) MPUExtrasGridSectionHeaderStyle * sectionHeaderStyle;
@property(assign,readwrite) bool showsScrollFade;
@property(assign,readwrite) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } videoCellSectionInsets;
@property(assign,retain) MPUExtrasGridCellStyle * videoCellStyle;
@property(assign,readwrite) double videoSpacing;

- (void).cxx_destruct;
- (bool)adjustsContentInsetByBottomNavBar;
- (id)backgroundColor;
- (double)cellLineSpacing;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })collectionViewInsets;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })defaultCellSectionInsets;
- (id)defaultCellStyle;
- (double)defaultSpacing;
- (id)detailDefaultFontAttributes;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })detailInsets;
- (id)detailTextColor;
- (id)detailTextStyle;
- (id)headerStyle;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })imageCellSectionInsets;
- (id)imageCellStyle;
- (double)imageSpacing;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })productCellSectionInsets;
- (id)productCellStyle;
- (double)productSpacing;
- (id)sectionHeaderStyle;
- (void)setAdjustsContentInsetByBottomNavBar:(bool)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setCellLineSpacing:(double)arg1;
- (void)setCollectionViewInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setDefaultCellSectionInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setDefaultCellStyle:(id)arg1;
- (void)setDefaultSpacing:(double)arg1;
- (void)setDetailDefaultFontAttributes:(id)arg1;
- (void)setDetailInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setDetailTextColor:(id)arg1;
- (void)setDetailTextStyle:(id)arg1;
- (void)setHeaderStyle:(id)arg1;
- (void)setImageCellSectionInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setImageCellStyle:(id)arg1;
- (void)setImageSpacing:(double)arg1;
- (void)setProductCellSectionInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setProductCellStyle:(id)arg1;
- (void)setProductSpacing:(double)arg1;
- (void)setSectionHeaderStyle:(id)arg1;
- (void)setShowsScrollFade:(bool)arg1;
- (void)setVideoCellSectionInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setVideoCellStyle:(id)arg1;
- (void)setVideoSpacing:(double)arg1;
- (bool)showsScrollFade;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })videoCellSectionInsets;
- (id)videoCellStyle;
- (double)videoSpacing;

@end
