/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicPlaylistProductMainViewController : MusicProductMainViewController <MusicMediaPickerDelegate> {
    UIImage *_editedPlaylistArtworkImage;
    MusicProductDescription *_editedPlaylistDescription;
    NSString *_editedPlaylistTitle;
    bool _forPlaylistCreation;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <MusicPlaylistProductMainViewControllerDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

- (void).cxx_destruct;
- (bool)_applyDeleteChangeRecord:(id)arg1 toPlaylist:(id)arg2;
- (bool)_applyInsertChangeRecord:(id)arg1 toPlaylist:(id)arg2;
- (bool)_applyMoveChangeRecord:(id)arg1 toPlaylist:(id)arg2;
- (void)_resetAdditionalMedatataViewController:(id)arg1;
- (void)_setEditedValue:(id)arg1 forProperty:(id)arg2 onPlaylist:(id)arg3 withSuccessfullyEditedPropertiesAccumulatorDictionary:(id)arg4;
- (void)_updateEditableComponents;
- (void)addProductToLibraryWithContainerEntityValueContext:(id)arg1;
- (void)cancelEditing;
- (void)commitEditingWithTracklistEntityProviderChangeRecords:(id)arg1;
- (void)configureProductAdditionalMetadataViewController:(id)arg1;
- (id)initWithContainerEntityProvider:(id)arg1 tracklistEntityProvider:(id)arg2 clientContext:(id)arg3 presentationSource:(long long)arg4;
- (id)initWithContainerEntityProvider:(id)arg1 tracklistEntityProvider:(id)arg2 clientContext:(id)arg3 presentationSource:(long long)arg4 forPlaylistCreation:(bool)arg5;
- (id)loadProductHeaderLockupContentDescriptor;
- (id)loadProductTracklistTableViewConfigurationWithTracklistEntityProvider:(id)arg1;
- (void)mediaPickerNavigationController:(id)arg1 didFinishWithSelectedEntities:(id)arg2;
- (void)productAdditionalMetadataViewControllerDidSelectAddSongsButton:(id)arg1;
- (void)productAdditionalMetadataViewControllerDidUpdateProductDescription:(id)arg1;
- (void)productHeaderLockupView:(id)arg1 didSelectCameraButton:(id)arg2;
- (void)productHeaderLockupViewDidSelectAddSongsButton:(id)arg1;
- (void)productHeaderLockupViewDidUpdateEditableText:(id)arg1;
- (void)setEditedPlaylistArtworkImage:(id)arg1;

@end
