/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicMediaPickerLibraryComposersViewConfiguration : MusicLibraryComposersViewConfiguration

- (long long)handleSelectionOfEntityValueContext:(id)arg1 fromViewController:(id)arg2;
- (id)loadEntityViewDescriptor;

@end
