/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface _MKScaleUnitsView : UIView {
    NSNumberFormatter *_floatNumberFormatter;
    double _justUnitsWidth;
    NSDictionary *_legendAttributes;
    NSString *_legendBaseString;
    NSMutableDictionary *_legendStringForDistanceStringCache;
    NSMapTable *_legendStringWidthCache;
    double _segmentLengthInPixels;
    NSMutableArray *_strings;
    NSString *_unitsString;
    double _unitsWidth;
    NSString *_unpaddedUnitsString;
    bool _useLightText;
}

@property(assign,retain) NSNumberFormatter * floatNumberFormatter;
@property(assign,retain) NSString * legendBaseString;
@property(assign,readwrite) double segmentLengthInPixels;
@property(assign,retain) NSString * unitsString;
@property(assign,readonly) double unitsWidth;
@property(assign,copy) NSString * unpaddedUnitsString;
@property(assign,readwrite) bool useLightText;

- (void).cxx_destruct;
- (void)_calculateLegend:(bool)arg1;
- (id)_legendStringForDistanceString:(id)arg1 appendUnits:(bool)arg2 index:(int)arg3;
- (id)_uncachedLegendStringsForDistanceString:(id)arg1;
- (double)_widthForString:(id)arg1 attributes:(id)arg2;
- (bool)canDisplaySegment:(unsigned long long)arg1;
- (void)clearCaches:(id)arg1;
- (id)floatNumberFormatter;
- (id)init;
- (id)legendBaseString;
- (void)setFloatNumberFormatter:(id)arg1;
- (void)setLegendBaseString:(id)arg1;
- (void)setSegmentLengthInPixels:(double)arg1;
- (void)setUnits:(id)arg1;
- (void)setUnitsString:(id)arg1;
- (void)setUnpaddedUnitsString:(id)arg1;
- (void)setUseLightText:(bool)arg1;
- (id)unitsString;
- (double)unitsWidth;
- (id)unpaddedUnitsString;
- (bool)useLightText;

@end
