/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKMapItemMetadataRequest : NSObject {
    MKMapItem *_mapItem;
}

@property(assign,retain) MKMapItem * mapItem;
@property(assign,readonly) NSURL * url;
@property(assign,readonly) NSURLRequest * urlRequest;

- (void).cxx_destruct;
- (void)handleData:(id)arg1;
- (void)handleError:(id)arg1;
- (id)mapItem;
- (void)setMapItem:(id)arg1;
- (id)url;
- (id)urlRequest;

@end
