/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IAP.framework/IAP
 */

@interface IAPClientPort : NSObject {
    NSObject<OS_dispatch_queue> *_clientPortEventQueue;
    id _sendDataHandler;
    NSObject<OS_dispatch_queue> *_sendDataHandlerQueue;
    NSString *_uuid;
}

@property(assign,readonly) NSObject<OS_dispatch_queue> * clientPortEventQueue;
@property(assign,readwrite) id sendDataHandler;
@property(assign,readonly) NSObject<OS_dispatch_queue> * sendDataHandlerQueue;
@property(assign,readonly) NSString * uuid;

- (id)clientPortEventQueue;
- (void)dealloc;
- (id)initWithUUID:(id)arg1 queue:(id)arg2 sendHandler:(id)arg3;
- (id)sendDataHandler;
- (id)sendDataHandlerQueue;
- (void)setSendDataHandler:(id)arg1;
- (id)uuid;

@end
