/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface CKDModifyRecordZonesURLRequest : CKDURLRequest {
    bool _markZonesAsUserPurged;
    NSMutableDictionary *_recordZoneIDByRequestID;
    NSArray *_recordZoneIDsToDelete;
    id _recordZoneModifiedBlock;
    NSArray *_recordZonesToSave;
}

@property(assign,readwrite) bool markZonesAsUserPurged;
@property(assign,retain) NSMutableDictionary * recordZoneIDByRequestID;
@property(assign,retain) NSArray * recordZoneIDsToDelete;
@property(assign,copy) id recordZoneModifiedBlock;
@property(assign,retain) NSArray * recordZonesToSave;

- (void).cxx_destruct;
- (id)initWithRecordZonesToSave:(id)arg1 recordZoneIDsToDelete:(id)arg2;
- (bool)markZonesAsUserPurged;
- (int)operationType;
- (id)recordZoneIDByRequestID;
- (id)recordZoneIDsToDelete;
- (id)recordZoneModifiedBlock;
- (id)recordZonesToSave;
- (void)requestDidParseNodeFailure:(id)arg1;
- (id)requestDidParseProtobufObject:(id)arg1;
- (id)requestOperationClasses;
- (id)requestOperations;
- (void)setMarkZonesAsUserPurged:(bool)arg1;
- (void)setRecordZoneIDByRequestID:(id)arg1;
- (void)setRecordZoneIDsToDelete:(id)arg1;
- (void)setRecordZoneModifiedBlock:(id)arg1;
- (void)setRecordZonesToSave:(id)arg1;
- (id)zoneIDsToLock;

@end
