/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface CKDModifyRecordZonesOperation : CKDDatabaseOperation {
    bool _allowDefaultZoneSave;
    id _deleteCompletionBlock;
    bool _markZonesAsUserPurged;
    int _numZoneSaveAttempts;
    NSMutableDictionary *_pcsOplockFailureCountByZoneID;
    NSArray *_recordZoneIDsToDelete;
    NSMutableDictionary *_recordZonesByZoneID;
    NSMutableArray *_recordZonesToSave;
    id _saveCompletionBlock;
}

@property(assign,readwrite) bool allowDefaultZoneSave;
@property(assign,copy) id deleteCompletionBlock;
@property(assign,readwrite) bool markZonesAsUserPurged;
@property(assign,readwrite) int numZoneSaveAttempts;
@property(assign,retain) NSMutableDictionary * pcsOplockFailureCountByZoneID;
@property(assign,retain) NSArray * recordZoneIDsToDelete;
@property(assign,retain) NSMutableDictionary * recordZonesByZoneID;
@property(assign,retain) NSMutableArray * recordZonesToSave;
@property(assign,copy) id saveCompletionBlock;

- (void).cxx_destruct;
- (void)_checkAndPrepareZones;
- (void)_fetchPCSDataForZone:(id)arg1 fromServer:(bool)arg2;
- (void)_fetchPCSDataForZonesFromServer:(bool)arg1;
- (void)_finishOnCallbackQueueWithError:(id)arg1;
- (void)_handleRecordZoneDeleted:(id)arg1 responseCode:(id)arg2;
- (void)_handleRecordZoneSaved:(id)arg1 responseCode:(id)arg2;
- (bool)_saveZonesToServer;
- (void)_sendErrorForFailedZones;
- (bool)allowDefaultZoneSave;
- (id)deleteCompletionBlock;
- (id)initWithOperationInfo:(id)arg1 clientContext:(id)arg2;
- (void)main;
- (bool)makeStateTransition;
- (bool)markZonesAsUserPurged;
- (id)nameForState:(unsigned long long)arg1;
- (int)numZoneSaveAttempts;
- (id)pcsOplockFailureCountByZoneID;
- (id)recordZoneIDsToDelete;
- (id)recordZonesByZoneID;
- (id)recordZonesToSave;
- (id)saveCompletionBlock;
- (void)setAllowDefaultZoneSave:(bool)arg1;
- (void)setDeleteCompletionBlock:(id)arg1;
- (void)setMarkZonesAsUserPurged:(bool)arg1;
- (void)setNumZoneSaveAttempts:(int)arg1;
- (void)setPcsOplockFailureCountByZoneID:(id)arg1;
- (void)setRecordZoneIDsToDelete:(id)arg1;
- (void)setRecordZonesByZoneID:(id)arg1;
- (void)setRecordZonesToSave:(id)arg1;
- (void)setSaveCompletionBlock:(id)arg1;

@end
