/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSSocketPairConnection : NSObject {
    long long _bytesReceived;
    int _connectedSocket;
    unsigned int _currentDataLength;
    NSMutableData *_currentMessageData;
    unsigned long long _currentOutgoingDataIndex;
    unsigned int _currentOutgoingFragmentedMessageID;
    IMWeakReference *_delegate;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    unsigned int _fragmentationSize;
    NSMutableData *_headerData;
    unsigned long long _inFlightMessageCountLowWaterMark;
    NSMutableDictionary *_incomingDataFragments;
    bool _isConnected;
    double _lastDateCheck;
    NSObject<OS_dispatch_semaphore> *_lock;
    bool _notifyWhenConnectionReceivesBytes;
    NSData *_outgoingData;
    NSMutableArray *_outgoingMessageArray;
    double _prevBPS;
    long long _priority;
    bool _writeSocketIsResumed;
}

@property (nonatomic) unsigned int fragmentationSize;
@property (nonatomic, readonly) unsigned long long inFlightMessageCount;
@property (nonatomic) unsigned long long inFlightMessageCountLowWaterMark;
@property (nonatomic, readonly) NSSet *inFlightMessages;
@property (nonatomic, readonly) bool isConnected;
@property (nonatomic, readonly) bool isEmpty;

- (void)_callDelegateWithBlock:(id)arg1;
- (void)_endSession;
- (void)_processBytesAvailable;
- (bool)_queueNextOutgoingData;
- (long long)_read:(char *)arg1 maxLength:(unsigned long long)arg2;
- (void)_sendToConnectedSocket;
- (void)dealloc;
- (void)endSession;
- (unsigned int)fragmentationSize;
- (unsigned long long)inFlightMessageCount;
- (unsigned long long)inFlightMessageCountLowWaterMark;
- (id)inFlightMessages;
- (id)initWithSocket:(int)arg1 queue:(id)arg2 delegate:(id)arg3 priority:(long long)arg4;
- (bool)isConnected;
- (bool)isEmpty;
- (bool)sendDataMessage:(id)arg1;
- (bool)sendDataMessage:(id)arg1 canFragment:(bool)arg2;
- (void)setFragmentationSize:(unsigned int)arg1;
- (void)setInFlightMessageCountLowWaterMark:(unsigned long long)arg1;
- (void)setNotifyWhenConnectionReceivesBytes:(bool)arg1;

@end
