/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSSocketPairResourceTransferSender : IDSSocketPairMessage {
    bool _compressed;
    bool _done;
    bool _expectsPeerResponse;
    int _fileDescriptor;
    unsigned int _maxChunkSize;
    NSString *_messageUUID;
    NSDictionary *_metadata;
    unsigned long long _nextByte;
    NSString *_peerResponseIdentifier;
    NSDictionary *_resourceAttributes;
    NSString *_resourcePath;
    bool _sentFirstMessage;
    unsigned int _sequenceNumber;
    unsigned short _streamID;
    unsigned long long _totalBytes;
    bool _wantsAppAck;
}

@property (nonatomic, readonly) bool isDone;
@property (nonatomic) unsigned int maxChunkSize;
@property (nonatomic, readonly, retain) NSString *messageUUID;
@property (nonatomic, readonly) bool sentFirstMessage;
@property (nonatomic) unsigned int sequenceNumber;

- (unsigned char)command;
- (void)dealloc;
- (id)description;
- (id)initWithResourceAtPath:(id)arg1 metadata:(id)arg2 sequenceNumber:(unsigned int)arg3 streamID:(unsigned short)arg4 expectsPeerResponse:(bool)arg5 wantsAppAck:(bool)arg6 compressed:(bool)arg7 peerResponseIdentifier:(id)arg8 messageUUID:(id)arg9;
- (bool)isDone;
- (unsigned int)maxChunkSize;
- (id)messageUUID;
- (id)nextMessage;
- (id)readNextBytes;
- (void)reset;
- (bool)sentFirstMessage;
- (unsigned int)sequenceNumber;
- (void)setMaxChunkSize:(unsigned int)arg1;
- (void)setSequenceNumber:(unsigned int)arg1;

@end
