/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKABPerson : GKABRecord

@property(assign,retain) GKABMultiValue * socialProfile;

- (id)emails;
- (void)setSocialProfile:(id)arg1;
- (id)socialProfile;
- (bool)updateSocialProfileWithPlayer:(id)arg1;

@end
