/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKFriendRecommendationInternal : GKFamiliarPlayerInternal {
    NSString *_reason;
    NSString *_reason2;
    unsigned int _rid;
    int _source;
}

@property(assign,retain) NSString * reason;
@property(assign,retain) NSString * reason2;
@property(assign,readwrite) unsigned int rid;
@property(assign,readwrite) int source;

+ (id)secureCodedPropertyKeys;

- (void)dealloc;
- (int)defaultFamiliarity;
- (id)reason;
- (id)reason2;
- (unsigned int)rid;
- (void)setReason2:(id)arg1;
- (void)setReason:(id)arg1;
- (void)setRid:(unsigned int)arg1;
- (void)setSource:(int)arg1;
- (int)source;

@end
