/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKVoiceChat : NSObject <GKVoiceChatSessionDelegate> {
    GKSession *_gkSession;
    GKVoiceChatSession *_gkVoiceChatSession;
    id _playerStateUpdateHandler;
    id _playerVoiceChatStateDidChangeHandler;
    NSArray *_players;
}

@property(getter=isActive,assign,readwrite) bool active;
@property(assign,retain) GKSession * gkSession;
@property(assign,retain) GKVoiceChatSession * gkVoiceChatSession;
@property(assign,copy) NSString * name;
@property(assign,copy) id playerStateUpdateHandler;
@property(assign,copy) id playerVoiceChatStateDidChangeHandler;
@property(assign,retain) NSArray * players;
@property(assign,readwrite) float volume;

+ (bool)isVoIPAllowed;

- (void)dealloc;
- (id)gkSession;
- (id)gkVoiceChatSession;
- (void)gkVoiceChatSession:(id)arg1 stateUpdate:(unsigned long long)arg2 forPeer:(id)arg3;
- (id)initChat:(id)arg1 withSession:(id)arg2 players:(id)arg3;
- (bool)isActive;
- (id)name;
- (id)playerIDs;
- (id)playerStateUpdateHandler;
- (id)playerVoiceChatStateDidChangeHandler;
- (id)players;
- (void)setActive:(bool)arg1;
- (void)setGkSession:(id)arg1;
- (void)setGkVoiceChatSession:(id)arg1;
- (void)setMute:(bool)arg1 forPlayer:(id)arg2;
- (void)setPlayer:(id)arg1 muted:(bool)arg2;
- (void)setPlayerStateUpdateHandler:(id)arg1;
- (void)setPlayerVoiceChatStateDidChangeHandler:(id)arg1;
- (void)setPlayers:(id)arg1;
- (void)setVolume:(float)arg1;
- (void)start;
- (void)stop;
- (float)volume;

@end
