/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@interface CMActivity : CMLogItem {
    struct CLMotionActivity { 
        int type; 
        int confidence; 
        int mountedState; 
        int mountedConfidence; 
        bool isStanding; 
        float tilt; 
        double timestamp; 
        int exitState; 
        double estExitTime; 
        double startTime; 
    } fActivity;
}

@property(assign,readonly) int confidence;
@property(assign,readonly) bool hasExitedVehicle;
@property(assign,readonly) bool isDriving;
@property(assign,readonly) bool isMoving;
@property(assign,readonly) bool isRunning;
@property(assign,readonly) bool isWalking;
@property(assign,readonly) bool maybeExitingVehicle;

+ (bool)supportsSecureCoding;

- (id).cxx_construct;
- (struct CLMotionActivity { int x1; int x2; int x3; int x4; bool x5; float x6; double x7; int x8; double x9; double x10; })activity;
- (int)confidence;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasExitedVehicle;
- (id)initWithCoder:(id)arg1;
- (id)initWithMotionActivity:(struct CLMotionActivity { int x1; int x2; int x3; int x4; bool x5; float x6; double x7; int x8; double x9; double x10; })arg1;
- (bool)isDriving;
- (bool)isMoving;
- (bool)isRunning;
- (bool)isWalking;
- (bool)maybeExitingVehicle;

@end
