/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
 */

@interface SFPeerDevice : NSObject <NSSecureCoding> {
    bool _defaultPairedDevice;
    NSString *_deviceColor;
    NSString *_enclosureColor;
    NSString *_modelIdentifier;
    NSString *_name;
    NSString *_productBuildVersion;
    NSString *_productName;
    NSString *_productVersion;
    NSString *_uniqueID;
}

@property(getter=isDefaultPairedDevice,assign,readwrite) bool defaultPairedDevice;
@property(assign,copy) NSString * deviceColor;
@property(assign,copy) NSString * enclosureColor;
@property(assign,copy) NSString * modelIdentifier;
@property(assign,copy) NSString * name;
@property(assign,copy) NSString * productBuildVersion;
@property(assign,copy) NSString * productName;
@property(assign,copy) NSString * productVersion;
@property(assign,copy) NSString * uniqueID;

+ (bool)supportsSecureCoding;

- (void)dealloc;
- (id)description;
- (id)deviceColor;
- (id)enclosureColor;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (bool)isDefaultPairedDevice;
- (bool)isEqual:(id)arg1;
- (id)modelIdentifier;
- (id)name;
- (id)productBuildVersion;
- (id)productName;
- (id)productVersion;
- (void)setDefaultPairedDevice:(bool)arg1;
- (void)setDeviceColor:(id)arg1;
- (void)setEnclosureColor:(id)arg1;
- (void)setModelIdentifier:(id)arg1;
- (void)setName:(id)arg1;
- (void)setProductBuildVersion:(id)arg1;
- (void)setProductName:(id)arg1;
- (void)setProductVersion:(id)arg1;
- (void)setUniqueID:(id)arg1;
- (id)uniqueID;

@end
