/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKAppDocument : NSObject <IKJSDOMDocumentAppBridge, IKStyleMediaQueryEvaluator> {
    IKAppContext *_appContext;
    <IKAppDocumentDelegate> *_delegate;
    NSError *_error;
    IKHeadElement *_headElement;
    NSString *_identifier;
    double _impressionThreshold;
    NSMutableSet *_impressions;
    NSMutableDictionary *_impressionsDict;
    IKDOMDocument *_jsDocument;
    JSManagedValue *_jsManagedDocument;
    IKViewElement *_navigationBarElement;
    IKJSObject *_owner;
    IKViewElementStyleFactory *_styleFactory;
    bool _subtreeUpdated;
    IKViewElement *_templateElement;
    IKViewElement *_toolbarElement;
    bool _updated;
}

@property(assign,readonly) IKAppContext * appContext;
@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <IKAppDocumentDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,retain) NSError * error;
@property(assign,readonly) unsigned long long hash;
@property(assign,retain) IKHeadElement * headElement;
@property(assign,retain) NSString * identifier;
@property(assign,readwrite) double impressionThreshold;
@property(assign,retain) NSMutableSet * impressions;
@property(assign,retain) NSMutableDictionary * impressionsDict;
@property(assign,readonly) IKDOMDocument * jsDocument;
@property(assign,retain) JSManagedValue * jsManagedDocument;
@property(assign,retain) IKViewElement * navigationBarElement;
@property(assign,readonly) IKJSNavigationDocument * navigationDocument;
@property(assign,readonly) IKJSObject * owner;
@property(assign,retain) IKViewElementStyleFactory * styleFactory;
@property(getter=isSubtreeUpdated,assign,readwrite) bool subtreeUpdated;
@property(assign,readonly) Class superclass;
@property(assign,retain) IKViewElement * templateElement;
@property(assign,retain) IKViewElement * toolbarElement;
@property(getter=isUpdated,assign,readwrite) bool updated;

- (void).cxx_destruct;
- (bool)_clearUpdatesForElement:(id)arg1;
- (void)_impressionDataFromViewElements:(id)arg1 timestamp:(long long)arg2 impressions:(id)arg3 impressionsDict:(id)arg4;
- (void)_updateWithXML:(id)arg1;
- (id)appContext;
- (void)dealloc;
- (id)delegate;
- (id)error;
- (bool)evaluateStyleMediaQueryList:(id)arg1;
- (id)headElement;
- (id)identifier;
- (double)impressionThreshold;
- (id)impressions;
- (id)impressionsDict;
- (id)initWithAppContext:(id)arg1 document:(id)arg2 owner:(id)arg3;
- (bool)isSubtreeUpdated;
- (bool)isUpdated;
- (id)jsDocument;
- (id)jsManagedDocument;
- (id)navigationBarElement;
- (id)navigationDocument;
- (void)onAppear;
- (void)onDisappear;
- (void)onLoad;
- (void)onNeedsUpdateWithCompletion:(id)arg1;
- (void)onUnload;
- (void)onUpdate;
- (void)onViewAttributesChangeWithArguments:(id)arg1 completion:(id)arg2;
- (id)owner;
- (void)recordImpressionsForViewElements:(id)arg1;
- (id)recordedImpressions;
- (id)retrieveJSElementForViewElement:(id)arg1 jsContext:(id)arg2;
- (void)runTestWithName:(id)arg1 options:(id)arg2;
- (void)scrollToTop;
- (void)setDelegate:(id)arg1;
- (void)setError:(id)arg1;
- (void)setHeadElement:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setImpressionThreshold:(double)arg1;
- (void)setImpressions:(id)arg1;
- (void)setImpressionsDict:(id)arg1;
- (void)setJsManagedDocument:(id)arg1;
- (void)setNavigationBarElement:(id)arg1;
- (void)setNeedsUpdateForDocument:(id)arg1;
- (void)setStyleFactory:(id)arg1;
- (void)setSubtreeUpdated:(bool)arg1;
- (void)setTemplateElement:(id)arg1;
- (void)setToolbarElement:(id)arg1;
- (void)setUpdated:(bool)arg1;
- (void)setViewElementStylesDirty;
- (id)snapshotImpressions;
- (id)styleFactory;
- (id)templateElement;
- (id)toolbarElement;
- (void)updateForDocument:(id)arg1;

@end
