/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKJSBlob : IKJSObject <IKJSBlob> {
    NSData *_data;
}

@property(assign,readonly) NSData * data;

- (void).cxx_destruct;
- (id)data;
- (id)initWithData:(id)arg1;

@end
