/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@interface GKSearchBarView : UICollectionReusableView <UISearchBarDelegate> {
    <UISearchBarDelegate> *_delegate;
    double _leadingMargin;
    GKSearchBar *_searchBar;
    NSArray *_searchBarConstraints;
    double _trailingMargin;
    NSNumber *_usePadConstraints;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,readwrite) <UISearchBarDelegate> * delegate;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readwrite) double leadingMargin;
@property(assign,retain) GKSearchBar * searchBar;
@property(assign,retain) NSArray * searchBarConstraints;
@property(assign,readonly) Class superclass;
@property(assign,readwrite) double trailingMargin;
@property(assign,readwrite) NSNumber * usePadConstraints;

+ (double)defaultHeight;
+ (void)initialize;
+ (bool)requiresConstraintBasedLayout;

- (void)applyLayoutAttributes:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (void)establishSearchBarConstraints;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (double)leadingMargin;
- (void)prepareForReuse;
- (id)searchBar;
- (id)searchBarConstraints;
- (void)setDelegate:(id)arg1;
- (void)setLeadingMargin:(double)arg1;
- (void)setSearchBar:(id)arg1;
- (void)setSearchBarConstraints:(id)arg1;
- (void)setTrailingMargin:(double)arg1;
- (void)setUsePadConstraints:(id)arg1;
- (double)trailingMargin;
- (void)updateConstraints;
- (id)usePadConstraints;

@end
