/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreHAP.framework/CoreHAP
 */

@interface HAPCharacteristic : NSObject {
    bool _eventNotificationsEnabled;
    NSNumber *_instanceID;
    HAPCharacteristicMetadata *_metadata;
    unsigned long long _properties;
    HAPService *_service;
    bool _shouldValidateValueAfterReading;
    NSString *_type;
    id _value;
}

@property (nonatomic) bool eventNotificationsEnabled;
@property (nonatomic, copy) NSNumber *instanceID;
@property (nonatomic, retain) HAPCharacteristicMetadata *metadata;
@property (nonatomic) unsigned long long properties;
@property (nonatomic) HAPService *service;
@property (nonatomic) bool shouldValidateValueAfterReading;
@property (nonatomic, readonly) bool supportsAdditionalAuthorizationData;
@property (nonatomic, copy) NSString *type;
@property (nonatomic, copy) id value;

- (void).cxx_destruct;
- (id)_generateValidMetadata:(id)arg1;
- (void)_updateMetadata:(id)arg1 withProvidedMetadata:(id)arg2;
- (id)description;
- (bool)eventNotificationsEnabled;
- (id)initWithType:(id)arg1 instanceID:(id)arg2 value:(id)arg3 properties:(unsigned long long)arg4 eventNotificationsEnabled:(bool)arg5 metadata:(id)arg6;
- (id)instanceID;
- (bool)isEqualToCharacteristic:(id)arg1;
- (id)metadata;
- (unsigned long long)properties;
- (id)propertiesDescription;
- (id)service;
- (void)setEventNotificationsEnabled:(bool)arg1;
- (void)setInstanceID:(id)arg1;
- (void)setMetadata:(id)arg1;
- (void)setProperties:(unsigned long long)arg1;
- (void)setService:(id)arg1;
- (void)setShouldValidateValueAfterReading:(bool)arg1;
- (void)setType:(id)arg1;
- (void)setValue:(id)arg1;
- (bool)shouldValidateValueAfterReading;
- (bool)supportsAdditionalAuthorizationData;
- (id)type;
- (id)validateValue:(id)arg1 outValue:(id*)arg2;
- (id)value;

@end
