/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPDAttribution : PBCodable <NSCopying> {
    NSMutableArray *_attributionUrls;
    NSString *_externalComponentId;
    NSString *_externalItemId;
    NSString *_vendorId;
}

@property(assign,retain) NSMutableArray * attributionUrls;
@property(assign,retain) NSString * externalComponentId;
@property(assign,retain) NSString * externalItemId;
@property(assign,readonly) bool hasExternalComponentId;
@property(assign,readonly) bool hasExternalItemId;
@property(assign,readonly) bool hasVendorId;
@property(assign,retain) NSString * vendorId;

+ (id)attributionForPlaceDataEntity:(id)arg1;
+ (id)attributionForPlaceDataPhotos:(id)arg1;
+ (id)attributionForPlaceDataReview:(id)arg1;

- (id)_attributionKey;
- (bool)_isYelp;
- (void)addAttributionUrl:(id)arg1;
- (id)attributionUrlAtIndex:(unsigned long long)arg1;
- (id)attributionUrls;
- (unsigned long long)attributionUrlsCount;
- (void)clearAttributionUrls;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)externalComponentId;
- (id)externalItemId;
- (bool)hasExternalComponentId;
- (bool)hasExternalItemId;
- (bool)hasVendorId;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setAttributionUrls:(id)arg1;
- (void)setExternalComponentId:(id)arg1;
- (void)setExternalItemId:(id)arg1;
- (void)setVendorId:(id)arg1;
- (id)vendorId;
- (void)writeTo:(id)arg1;

@end
