/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOTransitAppLaunchFeedbackCollection : PBCodable <NSCopying> {
    NSString *_bundleIdentifier;
    GEOLatLng *_destination;
    struct { 
        unsigned int timestamp : 1; 
    } _has;
    GEOLatLng *_source;
    double _timestamp;
}

@property(assign,retain) NSString * bundleIdentifier;
@property(assign,retain) GEOLatLng * destination;
@property(assign,readonly) bool hasBundleIdentifier;
@property(assign,readonly) bool hasDestination;
@property(assign,readonly) bool hasSource;
@property(assign,readwrite) bool hasTimestamp;
@property(assign,retain) GEOLatLng * source;
@property(assign,readwrite) double timestamp;

- (id)bundleIdentifier;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)destination;
- (id)dictionaryRepresentation;
- (bool)hasBundleIdentifier;
- (bool)hasDestination;
- (bool)hasSource;
- (bool)hasTimestamp;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setBundleIdentifier:(id)arg1;
- (void)setDestination:(id)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setSource:(id)arg1;
- (void)setTimestamp:(double)arg1;
- (id)source;
- (double)timestamp;
- (void)writeTo:(id)arg1;

@end
