/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCaptureMetadataOutputInternal_FigRecorder : NSObject {
    AVWeakReferencingDelegateStorage *delegateStorage;
    NSArray *metadataObjectTypes;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    } rectOfInterest;
}

- (void)dealloc;
- (id)init;

@end
