/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKScene : NSObject <NSCopying> {
    GEOTileKeyList *_debugKeyList;
    bool _fullyLoaded;
    VKTileKeyList *_keysInView;
    bool _mapIsOpaque;
    VKTileKeyList *_neighborKeys;
    NSSet *_neighborTiles;
    NSMutableArray *_rasterOverlayScenes;
    NSSet *_tilesToRender;
}

@property(assign,retain) GEOTileKeyList * debugKeyList;
@property(assign,readwrite) bool fullyLoaded;
@property(assign,retain) VKTileKeyList * keysInView;
@property(assign,readwrite) bool mapIsOpaque;
@property(assign,retain) VKTileKeyList * neighborKeys;
@property(assign,retain) NSSet * neighborTiles;
@property(assign,retain) NSSet * tilesToRender;

- (void)addRasterOverlayScene:(id)arg1;
- (void)clearRasterOverlayScenes;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)debugKeyList;
- (bool)fullyLoaded;
- (id)keysInView;
- (bool)mapIsOpaque;
- (id)neighborKeys;
- (id)neighborTiles;
- (id)rasterOverlaySceneAtLevel:(unsigned long long)arg1;
- (void)reset;
- (void)setDebugKeyList:(id)arg1;
- (void)setFullyLoaded:(bool)arg1;
- (void)setKeysInView:(id)arg1;
- (void)setMapIsOpaque:(bool)arg1;
- (void)setNeighborKeys:(id)arg1;
- (void)setNeighborTiles:(id)arg1;
- (void)setTilesToRender:(id)arg1;
- (id)tilesToRender;

@end
