/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIPopoverAnimationController : NSObject <UIViewControllerAnimatedTransitioning>

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

@end
