/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPrintPanelViewController : NSObject <UIPrinterBrowserOwner> {
    bool _animated;
    bool _dismissed;
    UINavigationController *_navigationController;
    UIPrintInfo *_observedPrintInfo;
    bool _observingRotation;
    UIViewController *_parentController;
    UIPopoverController *_poverController;
    UIPrintInteractionController *_printInteractionController;
    PKPrinter *_printer;
    UIPrintPanelTableViewController *_tableViewController;
    UIWindow *_window;
}

@property (nonatomic) long long copies;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool duplex;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) long long pageCount;
@property (nonatomic) struct _NSRange { unsigned long long x1; unsigned long long x2; } pageRange;
@property (nonatomic, retain) UIPrintPaper *paper;
@property (nonatomic, readonly) NSArray *paperList;
@property (nonatomic, retain) PKPrinter *printer;
@property (nonatomic, readonly) bool showCopies;
@property (nonatomic, readonly) bool showDuplex;
@property (nonatomic, readonly) bool showPageRange;
@property (nonatomic, readonly) bool showPaper;
@property (nonatomic, readonly) bool showPaperSelection;
@property (nonatomic, readonly) bool showPrinterWarning;
@property (readonly) Class superclass;

- (void)_keyWindowWillRotate:(id)arg1;
- (void)_presentInParentAnimated:(bool)arg1;
- (void)_presentWindow;
- (id)_removeRollsFrom:(id)arg1;
- (void)cancelPrinting;
- (long long)copies;
- (void)dealloc;
- (void)dismissAnimated:(bool)arg1;
- (void)dismissPrintPanel:(bool)arg1 animated:(bool)arg2;
- (bool)duplex;
- (bool)filtersPrinters;
- (id)initWithPrintInterationController:(id)arg1 inParentController:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (long long)pageCount;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })pageRange;
- (id)paper;
- (id)paperList;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)presentPrintPanelAnimated:(bool)arg1;
- (void)presentPrintPanelFromBarButtonItem:(id)arg1 animated:(bool)arg2;
- (void)presentPrintPanelFromRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inView:(id)arg2 animated:(bool)arg3;
- (void)printPanelDidDisappear;
- (void)printPaperViewDidDisappear;
- (void)printRangeViewDidDisappear;
- (id)printer;
- (void)printerBrowserViewDidDisappear;
- (void)setCopies:(long long)arg1;
- (void)setDuplex:(bool)arg1;
- (void)setPageRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (void)setPaper:(id)arg1;
- (void)setPrinter:(id)arg1;
- (bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (bool)showCopies;
- (bool)showDuplex;
- (bool)showPageRange;
- (bool)showPaper;
- (bool)showPaperSelection;
- (bool)showPrinterWarning;
- (void)startPrinting;
- (unsigned long long)supportedInterfaceOrientations;

@end
