/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISliderContent : NSObject {
    UIImage *maxTrack;
    UIImage *minTrack;
    UIImage *thumb;
}

@property(assign,readonly) bool isEmpty;
@property(assign,retain) UIImage * maxTrack;
@property(assign,retain) UIImage * minTrack;
@property(assign,retain) UIImage * thumb;

- (void)dealloc;
- (bool)isEmpty;
- (id)maxTrack;
- (id)minTrack;
- (void)setMaxTrack:(id)arg1;
- (void)setMinTrack:(id)arg1;
- (void)setThumb:(id)arg1;
- (id)thumb;

@end
