/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITableViewRowAction : NSObject <NSCopying> {
    UIColor *_backgroundColor;
    UIVisualEffect *_backgroundEffect;
    _UITableViewCellActionButton *_button;
    id _handler;
    long long _style;
    NSString *_title;
}

@property(assign,copy) UIColor * backgroundColor;
@property(assign,copy) UIVisualEffect * backgroundEffect;
@property(getter=_handler,assign,readonly) id handler;
@property(assign,readonly) long long style;
@property(assign,copy) NSString * title;

+ (id)rowActionWithStyle:(long long)arg1 title:(id)arg2 handler:(id)arg3;

- (id)_button;
- (id)_handler;
- (id)_initWithStyle:(id)arg1 title:(id)arg2 handler:(id)arg3;
- (void)_setButton:(id)arg1;
- (id)backgroundColor;
- (id)backgroundEffect;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (void)setBackgroundColor:(id)arg1;
- (void)setBackgroundEffect:(id)arg1;
- (void)setTitle:(id)arg1;
- (long long)style;
- (id)title;

@end
