/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ABLEModel.framework/ABLEModel
 */

@interface ABLEZeroAvoid : NSObject {
    double _decayRate;
    double _maximumLevel;
    double _minimumLevel;
}

@property(assign,readonly) double decayRate;
@property(assign,readonly) double maximumLevel;
@property(assign,readonly) double minimumLevel;

- (double)decayRate;
- (id)initWithDecayRatePerEntry:(double)arg1 minimumLevel:(double)arg2 maximumLevel:(double)arg3;
- (double)maximumLevel;
- (double)minimumLevel;
- (id)zeroAvoid:(id)arg1;

@end
