/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssertionServices.framework/AssertionServices
 */

@interface BKSProcess : BSBaseXPCClient {
    NSString *_bundlePath;
    NSObject<OS_dispatch_queue> *_clientQueue;
    bool _connectedToExternalAccessories;
    <BKSProcessDelegate> *_delegate;
    long long _exitStatus;
    bool _nowPlayingWithAudio;
    int _pid;
    bool _recordingAudio;
    bool _supportsTaskSuspension;
    int _taskState;
    long long _terminationReason;
    int _visibility;
    bool _workspaceLocked;
}

@property (nonatomic, readonly) double backgroundTimeRemaining;
@property (nonatomic) bool connectedToExternalAccessories;
@property (nonatomic) <BKSProcessDelegate> *delegate;
@property (nonatomic) long long exitStatus;
@property (nonatomic) bool nowPlayingWithAudio;
@property (nonatomic) bool recordingAudio;
@property (nonatomic) bool supportsTaskSuspension;
@property (nonatomic) int taskState;
@property (nonatomic) long long terminationReason;
@property (nonatomic) int visibility;
@property (nonatomic) bool workspaceLocked;

+ (double)backgroundTimeRemaining;
+ (id)busyExtensionInstances:(id)arg1;
+ (void)setTheSystemApp:(int)arg1 identifier:(id)arg2;

- (void)_handleDebuggingStateChanged:(id)arg1;
- (void)_handleExpirationWarning:(id)arg1;
- (void)_handleSuspendedStateChanged:(id)arg1;
- (void)_sendMessageType:(int)arg1 withMessage:(id)arg2;
- (void)_sendMessageType:(int)arg1 withMessage:(id)arg2 withReplyHandler:(id)arg3 waitForReply:(bool)arg4;
- (double)backgroundTimeRemaining;
- (bool)connectedToExternalAccessories;
- (void)dealloc;
- (id)delegate;
- (long long)exitStatus;
- (id)init;
- (id)initWithPID:(int)arg1 bundlePath:(id)arg2 visibility:(int)arg3 workspaceLocked:(bool)arg4 queue:(id)arg5;
- (bool)nowPlayingWithAudio;
- (void)queue_connectionWasCreated;
- (void)queue_connectionWasInterrupted;
- (void)queue_handleMessage:(id)arg1;
- (bool)recordingAudio;
- (void)setConnectedToExternalAccessories:(bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)setExitStatus:(long long)arg1;
- (void)setNowPlayingWithAudio:(bool)arg1;
- (void)setRecordingAudio:(bool)arg1;
- (void)setSupportsTaskSuspension:(bool)arg1;
- (void)setTaskState:(int)arg1;
- (void)setTerminationReason:(long long)arg1;
- (void)setVisibility:(int)arg1;
- (void)setWorkspaceLocked:(bool)arg1;
- (bool)supportsTaskSuspension;
- (int)taskState;
- (long long)terminationReason;
- (int)visibility;
- (bool)workspaceLocked;

@end
