/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface SFUPackageInputBundle : NSObject <SFUInputBundle> {
    NSString *_rootPath;
}

@property(assign,copy) NSString * debugDescription;
@property(assign,copy) NSString * description;
@property(assign,readonly) unsigned long long hash;
@property(assign,readonly) Class superclass;

- (id)_existingPathForEntryName:(id)arg1 isGz:(bool*)arg2;
- (id)bufferedInputStreamForEntry:(id)arg1;
- (void)copyEntry:(id)arg1 toFile:(id)arg2;
- (unsigned int)crc32ForEntry:(id)arg1;
- (void)dealloc;
- (bool)hasEntryWithName:(id)arg1;
- (id)initWithPath:(id)arg1;
- (id)inputStreamForEntry:(id)arg1;
- (long long)lengthOfEntry:(id)arg1;

@end
