/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartReferenceLineLabelPaddingLayoutItem : TSCHChartLayoutItem {
    TSCHChartAxisID *mAxisID;
}

@property(assign,retain) TSCHChartAxisID * axisID;

- (id)axisID;
- (struct CGSize { double x1; double x2; })calcMinSize;
- (void)dealloc;
- (id)initWithParent:(id)arg1 axisID:(id)arg2;
- (bool)p_hasReferenceLineLabels;
- (void)setAxisID:(id)arg1;

@end
