/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSPDocumentResourceCacheEntry : NSObject {
    NSURL *_URL;
    long long _accessCount;
    NSDate *_contentAccessDate;
    NSString *_digestString;
    long long _fileSize;
    bool _wasDownloaded;
}

@property(assign,copy) NSURL * URL;
@property(assign,readwrite) long long accessCount;
@property(assign,retain) NSDate * contentAccessDate;
@property(assign,readonly) NSString * digestString;
@property(assign,readwrite) long long fileSize;
@property(assign,readwrite) bool wasDownloaded;

- (void).cxx_destruct;
- (id)URL;
- (long long)accessCount;
- (id)contentAccessDate;
- (id)digestString;
- (long long)fileSize;
- (id)init;
- (id)initWithDigestString:(id)arg1;
- (void)setAccessCount:(long long)arg1;
- (void)setContentAccessDate:(id)arg1;
- (void)setFileSize:(long long)arg1;
- (void)setURL:(id)arg1;
- (void)setWasDownloaded:(bool)arg1;
- (bool)wasDownloaded;

@end
