/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSPPasteboardWriteAssistant : NSObject <TSPEncoderWriteCoordinatorDelegate, TSPPasteboardWriting, TSPProxyObjectMapping> {
    NSDictionary *_contentDescription;
    NSMutableDictionary *_dataProviderMap;
    NSMutableOrderedSet *_dataProviderTypes;
    bool _didAttemptToSerializeNativeData;
    TSPMemoryEncoder *_encoder;
    bool _excludeNativeData;
    long long _nativeDataOnceToken;
    TSPPasteboard *_nativeDataPasteboard;
    TSPPasteboardNativeDataProvider *_nativeDataProvider;
    TSPObjectContext *_pasteboardContext;
    TSPPasteboardObject *_pasteboardObject;
    bool _shouldRefuseAdditionalDataProviders;
    TSPEncoderWriteCoordinator *_writeCoordinator;
    long long _writeNativeDataToPasteboardOnceToken;
}

@property (nonatomic, copy) NSDictionary *contentDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool excludeNativeData;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) TSPObjectContext *pasteboardContext;
@property (nonatomic, readonly) TSPPasteboardObject *pasteboardObject;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (long long)componentWriterMode;
- (id)contentDescription;
- (id)createMetadataForRootObject:(id)arg1 dataArchiver:(id)arg2 objectUUIDToIdentifierDictionary:(id)arg3 externalReferences:(id)arg4 weakExternalReferences:(id)arg5 lazyReferences:(id)arg6 dataReferences:(id)arg7 error:(id*)arg8;
- (void)delayArchivingOfObject:(id)arg1;
- (bool)excludeNativeData;
- (id)initWithContext:(id)arg1;
- (void)loadData;
- (id)pasteboardContext;
- (id)pasteboardObject;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)proxyForReferencedObject:(id)arg1;
- (void)setContentDescription:(id)arg1;
- (void)setDataProvider:(id)arg1 forTypes:(id)arg2;
- (void)setExcludeNativeData:(bool)arg1;
- (void)setProxy:(id)arg1 forReferencedObject:(id)arg2;
- (bool)skipMetadataObjectSerialization;
- (id)tspPasteboardWithPasteboard:(id)arg1;
- (void)waitForNativeDataIfNeeded;
- (id)writableTypesForPasteboard:(id)arg1;
- (void)writeNativeDataToPasteboard:(id)arg1;

@end
