/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSUBool : NSObject {
    bool _value;
}

@property (nonatomic) bool value;

- (void)setValue:(bool)arg1;
- (bool)value;

@end
