/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface KeychainSyncSMSVerificationController : KeychainSyncTextEntryController <UIAlertViewDelegate> {
    NSString *_countryCode;
    NSString *_dialingPrefix;
    UIButton *_footerButton;
    PSKeychainSyncManager *_keychainSyncManager;
    NSString *_phoneNumber;
    UIAlertView *_supportVerificationAlert;
    unsigned long long _verificationCodeLength;
}

@property (nonatomic, retain) NSString *countryCode;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSString *dialingPrefix;
@property (readonly) unsigned long long hash;
@property (nonatomic) PSKeychainSyncManager *keychainSyncManager;
@property (nonatomic, retain) NSString *phoneNumber;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long verificationCodeLength;

- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (id)countryCode;
- (void)dealloc;
- (id)dialingPrefix;
- (void)dismissAlerts;
- (id)init;
- (id)keychainSyncManager;
- (void)loadView;
- (unsigned long long)numberOfPasscodeFields;
- (id)phoneNumber;
- (void)setCountryCode:(id)arg1;
- (void)setDialingPrefix:(id)arg1;
- (void)setKeychainSyncManager:(id)arg1;
- (void)setPhoneNumber:(id)arg1;
- (void)setVerificationCodeLength:(unsigned long long)arg1;
- (void)showSupportVerification;
- (id)specifiers;
- (unsigned long long)verificationCodeLength;
- (void)viewDidLayoutSubviews;

@end
