/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MusicCarDisplayUI.framework/MusicCarDisplayUI
 */

@interface MCDRadioViewController : MCD_OLD_TableViewController <RURadioDataSourceDelegate> {
    UIView *_MCD_tableView;
    RURadioDataSource *_dataSource;
    NSString *_featuredStationNamesBrief;
    NSArray *_featuredStations;
    NSArray *_myStations;
    MCDNoContentView *_placeholderView;
    RadioRecentStationsController *_recentStationsController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) RadioRecentStationsController *recentStationsController;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_categorizeStations;
- (bool)_isNetworkTypeAllowed:(long long)arg1;
- (void)_networkTypeDidChangeNotification:(id)arg1;
- (id)_stationFromIndexPath:(id)arg1;
- (void)_updateViewForNetworkType:(long long)arg1;
- (void)dealloc;
- (id)initWithPlayer:(id)arg1 serviceProvider:(id)arg2;
- (void)radioDataSourceDidInvalidate:(id)arg1;
- (id)recentStationsController;
- (void)setRecentStationsController:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)viewControllerForRowAtIndexPath:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
