/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuetDataModel.framework/CoreDuetDataModel
 */

@interface CDDMAppStateChangeEvent : NSManagedObject

@property(assign,retain) NSNumber * anonymizedBeacon;
@property(assign,retain) NSNumber * anonymizedLocation;
@property(assign,retain) NSNumber * appState;
@property(assign,retain) NSNumber * computeUtilization;
@property(assign,retain) NSDate * creationDate;
@property(assign,retain) NSNumber * integerId;
@property(assign,retain) NSNumber * ioBytes;
@property(assign,retain) NSNumber * ioBytesRead;
@property(assign,retain) NSNumber * ioBytesWritten;
@property(assign,retain) NSNumber * isFront;
@property(assign,retain) NSNumber * localDaysSinceSunday;
@property(assign,retain) NSNumber * localTime;
@property(assign,retain) NSNumber * localTimeQuarterHourSlot;
@property(assign,retain) NSNumber * memoryPhysicalFootprint;
@property(assign,retain) NSNumber * networkBytes;
@property(assign,retain) NSNumber * networkQuality;
@property(assign,retain) NSNumber * networkRxBytes;
@property(assign,retain) NSNumber * networkTxBytes;
@property(assign,retain) NSNumber * runReason;
@property(assign,retain) NSNumber * usedCellData;
@property(assign,retain) NSNumber * userId;

@end
