/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSMetricsClickEvent : SSMetricsBaseEvent

@property(assign,retain) id actionDetails;
@property(assign,retain) NSString * actionType;
@property(assign,retain) id impressions;
@property(assign,retain) NSString * locationDescription;
@property(assign,retain) NSNumber * positionX;
@property(assign,retain) NSNumber * positionY;
@property(assign,retain) NSString * targetIdentifier;
@property(assign,retain) NSString * targetType;
@property(assign,retain) NSString * targetURL;

- (id)actionDetails;
- (id)actionType;
- (id)description;
- (id)impressions;
- (id)init;
- (id)locationDescription;
- (id)positionX;
- (id)positionY;
- (void)setActionDetails:(id)arg1;
- (void)setActionType:(id)arg1;
- (void)setImpressions:(id)arg1;
- (void)setLocationDescription:(id)arg1;
- (void)setLocationWithEventLocations:(id)arg1;
- (void)setPositionX:(id)arg1;
- (void)setPositionY:(id)arg1;
- (void)setTargetIdentifier:(id)arg1;
- (void)setTargetType:(id)arg1;
- (void)setTargetURL:(id)arg1;
- (id)targetIdentifier;
- (id)targetType;
- (id)targetURL;

@end
